#### TASK 1 - The Business Scenario For FreshWave Telecom, Using Its Historical Customer Data For Three Separate Business
#### Questions From Three Different Teams - The Finance Team, The Retention Team, The Marketing Team, Using A SINGLE DATASET

####  THE PRESENTATION Report - WORK FLOW IDEA 

####  SCENARIO 1 

####  The Finance Team Of FreshWave Telecom Is Viewed As A Separate Client

####  THE BRIEF: 
####  To Find A Way To Estimate How Much Revenue A Customer Is Likely To Generate Based On Their Profile And The Services They 
####  Signed Up For - (Revenue Generation Estimates Of Customers With Telco Customers Churn Dataset.)

#### Addressing Scenario 1: Predicting Revenue, Preparing And Presenting The Findings As A Portfolio Project To The Finance Team

#### TASK 2 - Getting The Dataset From Kaggle

#### Importing Important Libraries

In [348]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Importing The Dataset

In [349]:
 TelcoCustomers = pd.read_csv("C:/Users/Mummy Utee/Downloads/TelcoCustomers/Telco_Customers_Churn.csv")

In [350]:
TelcoCustomers.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [351]:
TelcoCustomers

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

#### TASKS - NO 3

#####  DATA PREPARATION

##### STEP 1 - EXPLORING THE DATA SET TO GET IT INTO SHAPE FOR A MODEL

In [352]:
TelcoCustomers.shape

(7043, 21)

##### Displaying the 21 Columns To Identify Relevant Columns For Customers Profile And Services Subscribed To For Billing And Revenue
##### For The Finance Team

In [353]:
TelcoCustomers.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

##### Checking For Missing Values And Data Types

In [354]:
TelcoCustomers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [355]:
# TotalCharges column has numeric values but data type is not int64 or float64 as expected for building a moder but object.

TelcoCustomers['TotalCharges'].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

##### Checking For Null Values Within The Rows

In [356]:
TelcoCustomers.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [357]:
# No null values detected or observed with the 0 outcome above, in the 7043 rows of the 21 columns.

##### Observations Of The Data Types, For Necessary Data Cleaning Of Relevant Columns

In [359]:
# 1. Numerical Columns - Senior Citizen (int64), tenure (int64), Monthly Charges (float64), Total Charges (object) instead of int or float
#... Total Charges column with object data type indicates that some values are strings as either blank spaces or hypen (-) that needs to be 
#... converted to either integer or float..... after confirming whichever is the case,to determine the method of conversion of the object data type, 
#... using either astype(int), mean (average) or median, otherwise use pd.numeric and coerce errors, to NaN, then replace with

#... needs to be converted to either integer or float.

# 2. Categorical Columns - Other Columns have object data type because they are text and strings.

# 3. No missing row(s) observed or seen from the above as confirmed with all non-null count of the 7043 rows.
#... Columns total number is shown as 21 and total number of rows is from 0 - 7042 totalling 7043.

# 4. The data shape also confirms 7043 rows and 21 columns

##### Creating A Copy Of The Data Set For The Necessary Changes Of Data Types To Preserve The Original Dataset

In [360]:
TelcoCustomers_Copy = TelcoCustomers

TelcoCustomers_Copy = TelcoCustomers.copy()

In [361]:
TelcoCustomers_Copy

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

##### Converting Total Charges (Object) Column To Integer Or Float For Data Cleaning And Preparation

In [362]:
#  Checking For The Actual Values In All The Rows Of TotalCharges With Numerical Values But Showing Object Data Type To
#  Establish The Conversion Method To Use By Filtering The Column To See The Rows As Either Hypen, Text/Strings Or Blank

In [363]:
Filter = TelcoCustomers_Copy['TotalCharges']== ' '

In [364]:
TelcoCustomers_Copy[Filter]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [365]:
TelcoCustomers_Copy[Filter].value_counts

<bound method DataFrame.value_counts of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0
753   3115-CZMZD    Male              0      No        Yes       0
936   5709-LVOEQ  Female              0     Yes        Yes       0
1082  4367-NUYAO    Male              0     Yes        Yes       0
1340  1371-DWPAZ  Female              0     Yes        Yes       0
3331  7644-OMVMY    Male              0     Yes        Yes       0
3826  3213-VVOLG    Male              0     Yes        Yes       0
4380  2520-SGTTA  Female              0     Yes        Yes       0
5218  2923-ARZLG    Male              0     Yes        Yes       0
6670  4075-WKNIU  Female              0     Yes        Yes       0
6754  2775-SEFEE    Male              0      No        Yes       0

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ...
753           Yes                No              No  No internet service  ...
936           Yes                No             DSL                  Yes  ...
1082          Yes               Yes              No  No internet service  ...
1340           No  No phone service             DSL                  Yes  ...
3331          Yes                No              No  No internet service  ...
3826          Yes               Yes              No  No internet service  ...
4380          Yes                No              No  No internet service  ...
5218          Yes                No              No  No internet service  ...
6670          Yes               Yes             DSL                   No  ...
6754          Yes               Yes             DSL                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
488                   Yes                  Yes                  Yes
753   No internet service  No internet service  No internet service
936                   Yes                   No                  Yes
1082  No internet service  No internet service  No internet service
1340                  Yes                  Yes                  Yes
3331  No internet service  No internet service  No internet service
3826  No internet service  No internet service  No internet service
4380  No internet service  No internet service  No internet service
5218  No internet service  No internet service  No internet service
6670                  Yes                  Yes                  Yes
6754                   No                  Yes                   No

          StreamingMovies  Contract PaperlessBilling  \
488                    No  Two year              Yes
753   No internet service  Two year               No
936                   Yes  Two year               No
1082  No internet service  Two year               No
1340                   No  Two year               No
3331  No internet service  Two year               No
3826  No internet service  Two year               No
4380  No internet service  Two year               No
5218  No internet service  One year              Yes
6670                   No  Two year               No
6754                   No  Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
488   Bank transfer (automatic)          52.55                  No
753                Mailed check          20.25                  No
936                Mailed check          80.85                  No
1082               Mailed check          25.75                  No
1340    Credit card (automatic)          56.05                  No
3331               Mailed check          19.85                  No
3826               Mailed check          25.35                  No
4380               Mailed check          20.00                  No
5218               Mailed check          19.70                  No
6670               Mailed check          73.35                  No
6754  Bank transfer (automatic)          61.90                  No

[11 rows x 21 columns]>

##### Observations Of The Outcome Of The Filtered Total Charges Column And Other Columns Based On Value Counts 
##### For Insights About The Blank Rows That Created The Object Data Type

In [366]:
# 1. The 'TotalCharges' column, after it was filtered, showed 11 customers with blank rows, but with subscription details in the other 
#....columns, except the 'tenure' column with 0.

# 2. The value count of the filtered 'TotalCharges' column also showed the 'tenure' column without any previous tenure of services from  
#....the company.This gives an indication that the 11 blank rows are for new customers who had just subscribed for the services of the 
#....company and therefore had not yet recorded any used tenure, unlike the rest of the customers.

# 3. This also provides a guide as to the type of applicable conversion method... Using mean average or median does not apply
#....to blank spaces since there are no values. 

# 4. Conversion to integer with '.astype(int) gave ValueError'invalid literal for (int) with base 10:'29.85'). Converting the column 
#....did not work because of the 11 rows with blank spaces on the 'TotalCharges' column. 

# 5. The possible method to try therefore is to have the blank spaces changed to numeric values, with 'pd.to_numeric' code to give 
#....the 11 rows NaN values and then replace them with 0 values, with the 'fillna' code as float.

#####  Changing The Blank Spaces To NaN Before Replacing The NaN With Null Values

In [367]:
TelcoCustomers_Copy['TotalCharges'] = pd.to_numeric(TelcoCustomers_Copy['TotalCharges'], errors = 'coerce')

##### Checking To See The New And Changed Data Type Of TotalCharges Column

In [368]:
TelcoCustomers_Copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

##### Observations Of The TotalCharges Column After Changing The vData Type To Float64

In [369]:
# 1. The data type has been effectively changed from object to float64

# 2. The rows of TotalCharges column has reduced from 7043 to 7032, which indicates null values for the 11 rows with blank spaces 
#....are excluded that still need to be converted from NaN to float64 to have the complete 7043 rows converted to float64.

##### Checking To Confirm The Null Values Are The 11 rows Of Blank Spaces Changed To NaN

In [370]:
TelcoCustomers_Copy.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

##### Replacing The Null Values Of The II Rows With 0 To Have Non-Null Values

In [371]:
TelcoCustomers_Copy['TotalCharges'] = TelcoCustomers_Copy['TotalCharges'].fillna(0)

In [372]:
TelcoCustomers_Copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [452]:
TelcoCustomers_Copy.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
dtype: int64

In [374]:
# Observation Of Total Charges Column After The Final Conversion

# 1. Total Charges column now has complete 7043 rows with no blank spaces or null values again 

# 2. Total Charges column is now showing 0, and has become non-null like the other columns

# 3. Total Charges Column has also been fully converted from object to float64 to prepare the data set for building a model.

##### Checking The Data Set For Final Preparation To Get It Fully Ready For The Model

In [375]:
TelcoCustomers_Copy

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

##### Showing The Unique Values Of The Columns To Determine Needed Or Useful Columns For Estimating Revenue Generation
##### And The Contribution Of Each Customer, Based On Their Profile And The Services They Subscribed To, Required By The Finance Team.

In [376]:
TelcoCustomers_Copy.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [377]:
TelcoCustomers_Copy.describe  # The descriptive informaton shows both categorical and integer/float64 columns requiring actions

<bound method NDFrame.describe of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95       1889.50
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80       1990.50
7039              Yes    Credit card (automatic)         103.20       7362.90
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40        306.60
7042              Yes  Bank transfer (automatic)         105.65       6844.50

      Churn
0        No
1        No
2       Yes
3        No
4       Yes
...     ...
7038     No
7039     No
7040     No
7041    Yes
7042     No

[7043 rows x 21 columns]>

##### Checking The Unique Values Of All Columns To Determine Those To Drop For Estimating Revenue Generation Of Each Customer

In [378]:
# This column simply provides the identity of customers with no useful predictive values on revenue generation for the model.
# The identity of customers does not influence the estimate of likely revenue generation from customers.
# It should therefore be dropped.

TelcoCustomers_Copy['customerID'].unique()

array(['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', ..., '4801-JZAZL',
       '8361-LTMKD', '3186-AJIEK'], dtype=object)

In [379]:
# This column shows a binary categorical value and simply requires encoding for the chosen linear regression algorithm.

TelcoCustomers_Copy['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [380]:
TelcoCustomers_Copy['SeniorCitizen'].unique() # A combination Of old & new customers with the old billed, and new not billed yet.

array([0, 1])

In [381]:
TelcoCustomers_Copy['SeniorCitizen'].value_counts(normalize=True).round(2) # 84% new customers have no charges yet. Only 16% billed

SeniorCitizen
0    0.84
1    0.16
Name: proportion, dtype: float64

In [382]:
TelcoCustomers_Copy['SeniorCitizen'].value_counts()    # 5901 are new customers with no charges yet. 1142 are old and billed

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [383]:
TelcoCustomers_Copy['Partner'].unique()      #  They are customers/subscribers but special as partners

array(['Yes', 'No'], dtype=object)

In [384]:
TelcoCustomers_Copy['Partner'].value_counts()    # More than half of the customers/subscribers are Partners. This is useful.

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [385]:

TelcoCustomers_Copy['Partner'].value_counts(normalize=True).round(2)   # They have unique status as customers/subscribers

Partner
No     0.52
Yes    0.48
Name: proportion, dtype: float64

In [386]:
TelcoCustomers_Copy['Dependents'].unique()   # This gives a useful and additional information about the customer's subscription

array(['No', 'Yes'], dtype=object)

In [387]:
TelcoCustomers_Copy['tenure'].unique()   # This important for revenue generation estimates

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [388]:
# 1. This gives information about the tenure of each customer with an integer data type though does not adequately tell
#....the type of contract subscribed to by each customer which the contact column shows in terms of type and actual number
#....of customers for each type.

# 2. The 'tenure column' is directly related to the custmer's likely revenue generation estimates, and is therefore a useful column.
 

TelcoCustomers_Copy['tenure'].value_counts()

tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

In [389]:
#   This gives informative values on the proportion of each customer's tenure on the total tenure of all customers..
 
TelcoCustomers_Copy['tenure'].value_counts(normalize=True).round(2)

tenure
1     0.09
72    0.05
2     0.03
3     0.03
4     0.02
      ...
28    0.01
39    0.01
44    0.01
36    0.01
0     0.00
Name: proportion, Length: 73, dtype: float64

In [390]:
TelcoCustomers_Copy['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [391]:
TelcoCustomers_Copy['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [392]:
TelcoCustomers_Copy['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [393]:
TelcoCustomers_Copy['OnlineSecurity'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [394]:
TelcoCustomers_Copy['OnlineBackup'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [395]:
TelcoCustomers_Copy['DeviceProtection'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [396]:
TelcoCustomers_Copy['TechSupport'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [397]:
TelcoCustomers_Copy['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [398]:
TelcoCustomers_Copy['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [399]:
TelcoCustomers_Copy['Contract'].unique()       # The Different types of contract subscribed to by customers

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [400]:
TelcoCustomers_Copy['Contract'].value_counts()    # Shows types of contract, no of actual contract and duration of contract

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [401]:
TelcoCustomers_Copy['Contract'].value_counts(normalize=True).round(2)     # % of The different types of contract

Contract
Month-to-month    0.55
Two year          0.24
One year          0.21
Name: proportion, dtype: float64

In [402]:
TelcoCustomers_Copy['PaperlessBilling'].unique()

array(['Yes', 'No'], dtype=object)

In [403]:
TelcoCustomers_Copy['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [404]:
TelcoCustomers_Copy['MonthlyCharges'].unique()     # Total Charges Covers Monthly Charges Based On TENURE/CONTRACT

array([29.85, 56.95, 53.85, ..., 63.1 , 44.2 , 78.7 ])

In [405]:
TelcoCustomers_Copy['TotalCharges'].unique()

array([  29.85, 1889.5 ,  108.15, ...,  346.45,  306.6 , 6844.5 ])

In [406]:
TelcoCustomers_Copy['Churn'].unique()   # This indicates active customers(No) & those intending to stop services(Yes)

array(['No', 'Yes'], dtype=object)

In [407]:
TelcoCustomers_Copy['Churn'].value_counts() # Shows number of active customers to continue subscription (No) & Number likely to stop (Yes)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [408]:
TelcoCustomers_Copy['Churn'].value_counts(normalize=True).round(2) # Indicates 73% to stay active, 27% intending to stop services

Churn
No     0.73
Yes    0.27
Name: proportion, dtype: float64

#####  Analysis Of The DataSet From The Unique Values To Determine Columns To Drop, Features And Target Columns

In [293]:
# 1. The Dataset provides historical information about customer's profile to identify them, the services subscribed to for
#... billing, the service contract, monthly billing which translates into monthly payment of monthly charges and cummulates 
#... as total charges. A customer's profile and subscribed services is therefore the basis and determinig features for monthly 
#... billing and invariably monthly charges.

# 2. TO DROP CUSTOMER ID COLUMN

#... The customerID column is not a relevant or needed column because it is just an identifier of the customers and has no effect 
#... on historical revenue generated by customers as well as any current monthly charges 

# 3. CUSTOMER PROFILE AND SUBSCRIBED SERVICES COLUMNS FOR BILLING AND PAYMENTS AS FEATURES... REASONING AND JUSTIFICATION

# a. The columns for customer's profile and subscribed services apart from ID column are all useful as features columns and relevant
#... to predict the revenue estimates a customer is likely to generate on current basis and not on cummulative or historical revenue.
#... The profile abd billing features columns with int64/float64 are observed to have continuous values, indicating that a linear
#... regression model is chosen or decided to test and train the features columns for the prediction of likely revenue estimates that 
#... a Telco Customer can generate in a month.
# b. The binary features columns with Yes/No values need to be encoded, using map.apply to convert them to 0,1. 
# c. The other categorical features columns with a combination of mixed multiple texts and numerrical values, need to be encoded 
#... to 0,1 using One-HotEncoder, whiich is suitable and appropriate for features columns to make them readable for the model to learn 
#... and predict the likely revenue generation estimates of a customer as requested by the Finance Team.

# 4. MONTHLY CHARGES CONSIDERATION AND DECISION AS A MORE APPROPRIATE COLUMN TO USE AS TARGET FOR THE BUSINESS REQUEST. 
#... REASONING AND JUSTIFICATION

# a. The historical customer profile, 'tenure' and 'contract' records determine monthly revenue (monthly charges) based on
#... subscribed monthly services only. 
# b. 'Monthly charges' do not apply to all available services, but only to subscribed services in a month because 'tenure' and 'contract'
#... do not evenly apply or recur monthly for all customers. Monthly charges is therefore actual current charges. This is a more 
#... appropriate revenue measure to predict or estimate how much revenue a customer is likely to generate for sscenario 1.
# c. 'Monthly charges', based on current monthly billing is therefore considered the apprpriate customer 'revenue' genetated per month,
#... as the target column.

# 5. TO DROP TOTAL CHARGES COLUMN AND USE MONTHLY CHARGES COLUMN AS TARGET... REASONING AND JUSTIFICATION

# a..The 'total charges' (total revenue) on the other hand is historical and shows cummulative revenue generated. This includes 
#....various monthly services with different 'tenure', 'contract' months and type (month-to-month, 1-year or 2-years). 
# b..The data information about the 11 rows with blank spaces in 'total charges' column, due to 0 values on 'tenure; and 'senior citizens', 
#... is an indicatation the rows are for new customers and subscribers, who do not yet have historical billing and charges values, hence 0.
# c..The 'total charges' column drop is also considered necessary because it is closely related to both the 'tenure' and 'monthly charges' 
#....columns and the cummulative values indicated. 
# d..The column is also better dropped since, including it in the features columns could result in some data leakage in the model and cause
#....a misleading outcome, given that its relationship with 'tenure' is historical rather than the required likely estimate of how much 
#....'revenue' a customer can generate (current) as requested.
# e..All the considerations above, logically require that 'total charges' column be excluded and dropped from the predictive features columns 
#....required to determine the likely estimate of revenue generated by a customer and therefore not needed for the model. 

# 6. The basis for 'monthly charges' is just the sevices subscribed to in a month even though contact type may not be monthly and 
#....customers 'tenure' may also vary from month to month. Actual 'monthly charges' is therefore different from 'total charges'. 

# 7. TO DROP CHURN COLUMN... REASONING AND JUSTIFICATION

#... This column needs to be excluded because it is indicative of a customer's likely decision to stop subscribing for services, and a 
#... future outcome that is not a feature of current services subscribed to, for billing, revenue and payment. The churn indication and
#... situation invariably relates to a future outcome that has no effect whatsover on customer revenue generation estimates since the actual
#... churn information is not yet available for the customer revenue estimate.

##### Dropping Columns Not Needed To Estimate How Much Revenue A Customer Is Likely To Generate Based On Their
##### Profile And The Services They Signed Up For, As Required By The Finance Team For The Regression Model

In [409]:
TelcoCustomers_Copy = TelcoCustomers_Copy.drop(columns=['customerID','TotalCharges', 'Churn'])

##### Checking To Confirm The Columns Listed Are Dropped

In [410]:
print(TelcoCustomers_Copy.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges']

In [411]:
TelcoCustomers_Copy.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges'],
      dtype='object')

##### Encoding Categorical Features Customer Profile And Services Columns With Binary Values Using Mapping

In [412]:
TelcoCustomers_Copy['gender'] = TelcoCustomers_Copy['gender'].map({'Female': 0, 'Male': 1})
TelcoCustomers_Copy['Partner'] = TelcoCustomers_Copy['Partner'].map({'No': 0, 'Yes': 1})
TelcoCustomers_Copy['Dependents'] = TelcoCustomers_Copy['Dependents'].map({'No': 0, 'Yes': 1})
TelcoCustomers_Copy['PhoneService'] = TelcoCustomers_Copy['PhoneService'].map({'No': 0, 'Yes': 1})
TelcoCustomers_Copy['PaperlessBilling'] = TelcoCustomers_Copy['PaperlessBilling'].map({'No': 0, 'Yes': 1})

##### Checking To Confirm Encoding Of The Binary Features Values

In [413]:
TelcoCustomers_Copy

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,1,Mailed check,84.80
7039,0,0,1,1,72,1,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,1,Credit card (automatic),103.20
7040,0,0,1,1,11,0,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,1,Electronic check,29.60
7041,1,1,1,0,4,1,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Mailed check,74.40
7042,1,0,0,0,66,1,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65

In [415]:
TelcoCustomers_Copy.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges'],
      dtype='object')

##### Separating The Dataset Into Features And Target

In [300]:
X = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Y = ['MonthlyCharges']

In [302]:
Features = X
Target = Y

X = Features
Y = Target

X = TelcoCustomers_Copy.drop(columns=['MonthlyCharges'])   # Features
Y = TelcoCustomers_Copy['MonthlyCharges']                   # Target

##### Splitting The Dataset Into Training And Testing Sets Before Encoding As Appropriate

In [303]:
from sklearn.model_selection import train_test_split

In [304]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [305]:
X_train

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
2142,0,0,0,1,21,1,No,DSL,Yes,No,Yes,No,No,Yes,One year,0,Mailed check
1623,0,0,0,0,54,1,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Two year,1,Bank transfer (automatic)
6074,1,0,1,0,1,0,No phone service,DSL,No,No,No,No,No,No,Month-to-month,1,Electronic check
1362,1,0,0,0,4,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check
6754,1,0,0,1,0,1,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,1,Bank transfer (automatic)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,1,0,1,0,1,1,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,1,Electronic check
5191,0,0,1,1,23,1,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,1,Credit card (automatic)
5226,1,0,1,1,12,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,1,Electronic check
5390,1,1,0,0,12,1,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,1,Electronic check
860,1,0,0,0,26,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,0,Credit card (automatic)

In [306]:
X_test

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
185,0,0,1,0,1,0,No phone service,DSL,No,No,No,No,No,No,Month-to-month,1,Electronic check
2715,1,0,0,0,41,1,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,1,Bank transfer (automatic)
3825,0,0,1,1,52,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,0,Mailed check
1807,0,0,0,0,1,1,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,0,Electronic check
132,1,0,0,0,67,1,No,DSL,No,No,No,Yes,No,No,Two year,0,Bank transfer (automatic)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,0,0,1,0,64,1,No,DSL,No,Yes,Yes,Yes,No,Yes,Two year,1,Mailed check
315,1,0,1,1,51,1,Yes,Fiber optic,Yes,Yes,No,Yes,Yes,Yes,One year,0,Credit card (automatic)
2439,1,0,1,1,17,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,0,Bank transfer (automatic)
5002,0,0,1,1,69,0,No phone service,DSL,Yes,No,Yes,No,No,Yes,Two year,1,Credit card (automatic)
1161,1,0,0,1,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Mailed check

In [307]:
Y_train

2142    64.85
1623    97.20
6074    23.45
1362    70.20
6754    61.90
        ...
3772    95.00
5191    91.10
5226    21.15
5390    99.45
860     19.80
Name: MonthlyCharges, Length: 5634, dtype: float64

In [308]:
Y_test

185      24.80
2715     25.25
3825     19.35
1807     76.35
132      50.55
         ...
6366     68.30
315     110.05
2439     19.90
5002     43.95
1161     31.35
Name: MonthlyCharges, Length: 1409, dtype: float64

##### Checking The Shape Of The Training And Test Sets Split

In [309]:
print(f'Training Set:{X_train.shape}')
print(f'Testing Set:{X_test.shape}')

Training Set:(5634, 17)
Testing Set:(1409, 17)

##### Encoding The remaining Categorical Features Columns With Multiple Combination Of Text And Numerical Values Using One-HotEncoder 
##### Since The Columns Are Features To Covert The Values To Binary

In [416]:
# Defining The Categorical Columns With Multiple Text And Numerical Values

Categorical_Columns = ['MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaymentMethod']

In [417]:
from sklearn .preprocessing import OneHotEncoder

##### Creating An Instance Of OneHotEncoder Using Dummy

In [418]:
Encode = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)

##### Fitting Only Categorical Columns With Multiple Text And Binary Values, Excluding THe Already Numeric Binary Values Columns

In [314]:
# Fitting On Only Categorical Columns Of X_train And Transforming X_test

X_train_Encoded = Encode.fit_transform(X_train[Categorical_Columns])
X_test_Encoded = Encode.transform(X_test[Categorical_Columns])

In [315]:
X_train_Encoded

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [316]:
X_train_Encoded.shape

(5634, 31)

In [317]:
X_test_Encoded

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [318]:
X_test_Encoded.shape

(1409, 31)

In [319]:
print(Categorical_Columns)

['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

In [320]:
print('Number of categorical columns:', len(Categorical_Columns))

Number of categorical columns: 10

In [321]:
print (X_train[Categorical_Columns].shape)

(5634, 10)

In [322]:
print(X_test[Categorical_Columns].shape)

(1409, 10)

#####  Analysis Of Obsevations On The Encoded Columns

In [323]:
# Observations And Reasoning On The OneHotEncoder And Mapping Conversion Of Categorical Columns To Numeric

# 1. The encoding actions only focused on the remaining categorical features columns with the combined text and binary values.
# 2. Those categorical columns are with OneHotEncoder, applied only on features columns, converted to numeric. 
# 3. These columns are now named X_train_Encoded

# Observaytions Of The Mapping On The Binary Columns (yes/No) 

# 1. Only a few binary columns were converted to numeric.
# 2. Those binary-numeric columns were excluded from the OneHotEncoding action and effects.
# 3. These columns are still X-train

# Implications Of The Separate Actions

# 1. The features columns, though already converted to numeric, with separated and different applications of convertion 
#....methods are now X-train and X_train_encoded
# 2. This separate features (X) columns of categorical numeric-binary (X_train) and categorical numeric-multiple text/binary
#....(X_train_Encoded and need to be merged together to have a single features for training and testing of equal rows as 
#....Y_train and Y_test. 

#  Required Actions

# 1. To merge the entire categorical mapped binary features columns with the encoded text and binary features columns, all 
#....converted to numeric, and have a combined and single numeric features columns required to complete the data preprocessing 
#....and preparation for building a model to estimate the likely estimate of revenue a customer can generate for the Finance Team.

#####  Combining the Numeric Binary Columns And Numeric Categorical Encoded Columns

#####  1 - Converting The Encoded Values (Arrays) To DataFrames To Be Able To Combine Them With The Numeric And Binary_Mapped
#####      And Encoded Columns As A Single Features Columns

In [324]:
X_train_Encoded = pd.DataFrame(X_train_Encoded, columns=Encode.get_feature_names_out(Categorical_Columns), index=X_train.index)
X_test_Encoded = pd.DataFrame(X_test_Encoded, columns=Encode.get_feature_names_out(Categorical_Columns), index=X_test.index)

##### 2 - Listing And Identifying The Numeric And Binary-Mapped Encoded Columns Still Reflected As X_Train

In [325]:
X_train_Numeric = [Columns for Columns in X_train if Columns not in Categorical_Columns]
X_test_Numeric = [Columns for Columns in X_test if Columns not in Categorical_Columns]

##### 3 - Combining X_train (Numerical int64/float64 Columns And Numerical Binary-Mapped Columns) With The Encoded Multiple
#####     Categorical Text And Binary Values, To Have A Complete Single Features Columns For The Model For Both Training And
#####     Testing Sets Using pd.concat( ) As A Better Application Than Using Concat

In [326]:
X_train_Combined = pd.concat([X_train[X_train_Numeric], X_train_Encoded], axis = 1)

In [327]:
X_test_Combined = pd.concat([X_test[X_test_Numeric], X_test_Encoded], axis = 1)

In [328]:
print(X_train_Combined.shape)

(5634, 38)

In [329]:
print(X_test_Combined.shape)

(1409, 38)

In [330]:
print(X_train_Combined.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'PaperlessBilling', 'MultipleLines_No', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_DSL', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [331]:
Y_train

2142    64.85
1623    97.20
6074    23.45
1362    70.20
6754    61.90
        ...
3772    95.00
5191    91.10
5226    21.15
5390    99.45
860     19.80
Name: MonthlyCharges, Length: 5634, dtype: float64

In [332]:
Y_test

185      24.80
2715     25.25
3825     19.35
1807     76.35
132      50.55
         ...
6366     68.30
315     110.05
2439     19.90
5002     43.95
1161     31.35
Name: MonthlyCharges, Length: 1409, dtype: float64

In [333]:
X_train_Combined

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
2142,0,0,0,1,21,1,0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1623,0,0,0,0,54,1,1,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6074,1,0,1,0,1,0,1,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1362,1,0,0,0,4,1,1,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6754,1,0,0,1,0,1,1,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,1,0,1,0,1,1,1,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
5191,0,0,1,1,23,1,1,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
5226,1,0,1,1,12,1,1,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
5390,1,1,0,0,12,1,1,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
860,1,0,0,0,26,1,0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [334]:
X_test_Combined

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
185,0,0,1,0,1,0,1,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2715,1,0,0,0,41,1,1,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3825,0,0,1,1,52,1,0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1807,0,0,0,0,1,1,0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
132,1,0,0,0,67,1,0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,0,0,1,0,64,1,1,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
315,1,0,1,1,51,1,0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2439,1,0,1,1,17,1,0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
5002,0,0,1,1,69,0,1,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1161,1,0,0,1,1,0,1,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

##### Choice Of Model To Predict Revenue Estimate The Revenue That A Telco Customer Is Likely To Generate Based On Their Profile And Subscribed Services, As requested By The Finance Team - 
##### LINEAR REGRESSION ALGORITHM MODEL

##### Reasoning And Decision For The Choice Of Linear Regression Algorithm

In [335]:
#    THE DATASET

# 1. The Telco Customers Dataset is a combination of different categories of features (X) data values with 21 columns, 
#....and a target column (Y).

# 2. The break-down of the different categories of the data values and their data types shows some of the feature columns 
#....with continuous numerical values, combined with other categorical columns with simpleas binary values and multiple
#....categories of texts, as well as simple and more complex binary values. 

# 3  The dataset are also labelled with inputs resulting in known outputs as the predictor columns for a supervised learning.

# 4  The labelled datasets show the relationship between inputs and outputs (independent i.e. features (X) and dependent i.e.
#....target (Y) values, for predicting a continuous values of target (Y) of labels of unseen and new data with a machine learning
#....algorithm, wherein inputs result in known outputs when a machine model learns and trains the datasets with the predictor
#....values, using the a regression model, appropriately considered to be linear regression algorithm.

#    THE DECISION FOR A LINEAR REGRESSION AS A MORE APPROPRIATE ALGORITHM FOR BUILDING A PREDICTIVE MODEL

# 1. The continuous numerical 'tenure' feature column values cleary and definitely support the use of Linear Regression model
#....in spite of the other categorical features columns.

# 2. The already known and/or  pre-determined values of the 'tenure' column from Telco customers profiles and subsribed services
#....provides the trade-off for the choice of linear regression algorithm over logistic regression algorithm.

# 3. The Finance Team request for the estimate of revenue that a customer is likely to generate, based on their profile and the 
#....services signed for can therefore be predicted with a linear regression model with the features columns identified and 
#....retained and the target column of Monthly Charges considered more appropriate to determine and predict a customer revenue
#....estimate than the historical and cumulative dropped Total Charges column which is more approriate for cumulative revenue
#....over previous periods and not current revenue estimate.

##### Importing The Machine Learning Algorithm To Use For The Model

In [420]:
from sklearn.linear_model import LinearRegression

##### Creating An Instance Of The Model For The Prediction Of Revenue Estimate A Telco Customer Is Likely To Generate To the
##### Finance Team Of FreshWave Telecom Based On Customer Profile And Services Signed For.

In [421]:
 FTModel = LinearRegression()

##### Fitting The Training Dataset Into The Model To Predict The Revenue Estimate A Telco Customer Is Likely To Generate
##### To The Finance Team Of FreshWave Telecom Based On Customer Profile And Services Signed For.

In [422]:
FTModel.fit(X_train_Combined, Y_train)

LinearRegression()

In [423]:
y_predictions = FTModel.predict(X_test_Combined)

In [424]:
print(type(y_predictions))
print(y_predictions.shape)
print(y_predictions[:5])

<class 'numpy.ndarray'>
(1409,)
[24.95966268 24.98735779 19.92427981 74.96775079 50.00388654]

##### Observation Of The Prediction Results Or Outcome Of The Estimate Of The Revenue A Telco Customer Is Likely To Generate
##### To The Finance Team Of FreshWave Telecom Based On Customer Profile And Services Signed For.

In [425]:
# 1. The Finance Team Model (FTModel) predicted revenue estimate a Telco customer is likely to generate as a continuous value.

# 2. The predicted outcome justifies the trade-off and the decision for the use of Linear Regression algorithm to build the model
#....to present to the Finance Team.

##### Checking To Confirm The Values Of The Variables Trained, Fitted, Predicted And Tested

In [426]:
X_train_Combined.shape

(5634, 38)

In [427]:
X_test_Combined.shape

(1409, 38)

In [428]:
Y_train.shape

(5634,)

In [429]:
Y_test.shape

(1409,)

In [430]:
print('X_test_Combined:', X_test_Combined.shape)
print('Y_test:', Y_test.shape)
print('y_predictions:', y_predictions.shape)

X_test_Combined: (1409, 38)
Y_test: (1409,)
y_predictions: (1409,)

In [431]:
print(type(y_predictions))
print(y_predictions)

<class 'numpy.ndarray'>
[24.95966268 24.98735779 19.92427981 ... 19.95950489 44.9247107
 29.94193257]

##### Evaluating The Finance Team Linear Regression Model With Relevant And Appropriate Metrics - Mean Absolute Error (MAE),
##### Mean Squared Error (MSE), Root Mean Squared Error (RMSE), R-Squared (r2)

In [432]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

##### Evaluating The Model With The Metrics

In [433]:
MAE = mean_absolute_error(Y_test, y_predictions)

In [434]:
MAE

0.7892749564822678

In [435]:
MSE = mean_squared_error(Y_test, y_predictions)

In [436]:
MSE

1.105210411209106

In [437]:
RMSE = np.sqrt(1.105210411209106)

In [438]:
RMSE

np.float64(1.0512898797235262)

In [439]:
r2 = r2_score(Y_test, y_predictions)

In [440]:
r2

0.998779278341754

##### Checking The FTModel Score

In [441]:
print('FTModel score:', FTModel.score(X_test_Combined, Y_test))

FTModel score: 0.998779278341754

##### To Know Or Estimate How Much Revenue A Telco Customer Can Likely Generate For The Finance Team

In [450]:
Test_Predictions = FTModel.predict(X_test_Combined)

In [451]:
print(Test_Predictions)

[24.95966268 24.98735779 19.92427981 ... 19.95950489 44.9247107
 29.94193257]

In [ ]:
# The FTModel's prediction above varies from one customer to another and depends on subsribed services

# While it shows a customer generating 24.96 monthly charges, another is generating 44.92.

####  Findings, Interpretation Analysis And Evaluation Metrics Of The Model Predictions

In [ ]:
# 1.   EXECUTIVE SUMMARY OF THE FINDINGS

#    The Telco customers churn dataset, checked, explored, prepared, preprocessed and fitted into the model to address the 
#....concerns of the Finance Team, with the relevant and necessary information for the task gave predictive insghts required 

# 2.   APPROACH 

#    The observation of the dataset showed that a supervised machine learning algorithm that learns the relationship between
#....the customer infomaton and records as the predictor indicators to establish the revenue predictions. Current monthly charges
#....was viewed a better and more appropriate revenue base consideration, than the cumulative historical total charges. This is 
#....due to the cumulative revenue effects that tenure of services with varied number of months and different contract types, have
#....on the cumulative charges.


# 3.  EVALUATION METRICS OF THE MODEL

#    This was done with the following relevant metrics to establish the required findings and present to the Finance Team:

# 1. Mean_Absolute_Error (MAE)

#    The outcome of 0. 7892749564822678 (0.789) is the measure of the difference between the predicted values and the actual
#....values. It shows a slight differece of about 0.79 variance (+ or -) from the actual values which confirms there are no 
#....significant prediction errors from the features predictors. A lower MAE generally indicates a better performance, with 
#....0 as perfect. The 0.79 result of the model indicates a good level of reliability for the predictive performance of the 
#....regression model to address the request of the Finance Team.

# 2. Mean_Squared_Error (MSE) 

#    The value is 1.105210411209106 shows or measures the average of of squared differences between the predicted and actual values.
#....The level of the squared errors of this moderl with 1.105 suggests a relatively small predictive  errors of the model. It 
#....This however depends on the scale or volume of the target variable for interpretation. A lower MSE is preferred as indicating
#....a good prediction, with 0 as a perfect prediction level. This regression model score of 1.105, confirms a relatively low error
#....margin.

# 3. Root Mean Squared Error (RMSE)

#    This is simply the square root of MSE with the regression model outcome of 1.0512898797235262 (1.05) indicating a prediction
#....error magnitude or volume of about 1.05 on the target monthl charges values. a larger RMSE result will have a greater effect 
#....and influence on the target units.

# 4. r2_Score (r2)

#    The score of 0.998779278341754 (0.9987) is indicate of a high and good result of the regression model for the prediction of 
#....revenue estimate that a Telco customer is likelt to generate. The r2 score shows that the model is able to explain or measure 
#....how much variation there is, with the target values of monthly charges. The r2 result shows that  the regression model was able
#....to handle up to 99.88% of the variation with target monthly charges and only about 0.12% of the variation was not explained by 
#....the model, which is reasonably very low, and also explains a good fit of the model, though a result of 1.0 or 100% gives a
#....perfect fit.

# 5.    TEST PREDICTIONS OF REVENUE ESTIMATE A CUSTOMER IS LIKELY TO GENERATE AS REQUESTED 

#       [24.95966268 24.98735779 19.92427981 ... 19.95950489 44.9247107
#       29.94193257]


# General Comments

# 1. On the whole, the Telcom Customers dataset with their profile and subsrcibed services, with monthly charges as dependent
#....target variable, and the relevant predictor features as independent variable, using the regression model on the
#....the interpretation above, summarizes anly 0.79 units of average prediction error, which is a relatively small mean squared 
#....prediction error, with an error volume of 1.05 and  r2 score of 0.998779278341754 (0.998779), explaining a 99.88% 
#....variation with monthly charges, is consistent with actual model score of 0.998779278341754 (0.9988779) or 99.88%, with a small
#....error magin of 0.12%. This makes the model reliable for the prediction of the likely revenue estimate that a Telco customer can
#....generate.

# 2. The model also shows a good and well fitted actual values of the profile and subscribed services to the predicted values.

# 3. On the other hand, the very high r2 score of 99.88% which needs to be verified further to confirm there was no data leakage and
#....overfitting of the training sample data and the test data are accurate and correctly independent to ensure a cautious assessment 
#....of the model and the predictions as excellent and almost a 100% perfect fit.


# 4.     FINDINGS AND CONCLUSION

#    The findings below indicate that based on the current services indices, the revenue a customer generates is sustainable and 
#....predictable based on the paramters of subscribed services. 

#....The show the closeness of the predictions outcome of revenue estimate a customer can generate, to be dependent the numerical 
#....strength and capacity of customers, the quality and volume of services provided, and signed up for by customers, as closely 
#....related to the revenue predictions.

#....The predictions as established, also reliably confirms that same level of services and charges need to apply to new customers 
#....in order to achieve the same level of revenue performance, with potential revenue increase with more new customers,that will
#....generate more revenue. This shows a direct relationship between number of customers, available range of service and delivery 
#....capacticy. This predictors are indicators for continued increased revenue performance, at least, with the same level of 
#....customer numbers, and more new customers, and service delivery efficiency and new services.fficiency and.

#.... The findings also suggest a strong going-concern status of Telco, confirming that the company will continue in business in the 
#.... forseable future with a good performance level of revenue generation and profitability, that will continue to sustain the business,
#.... provided that the current business customer profile and subscribed services are maintained, sustained, increased and kept efficiently.

#     The going-concern status and good business prospects of Telco is further is assured and confirmed with the predictions, given that 
#.... 84% of Telco customers who are senior citizens, which translates to 5,901 customers are currently new with 0 charges, with likely 
#.... tendency to need the services.

#.... The 99.88% prediction performance of the model, in terms of explaining and covering the variation between the level of current
#.... revenue a customer can likely generate, and new actual level of future revenue generation, with only 0.12% (= or -) variation
#.... or difference is indicative of a possibility of higher revenue estimate a customer will generate for Telco to continue thriving
#.... with more volume of business from customers.

# 5.  The test predictions of FTModel's of the revenue a customer is likely to generate above, the varibility from one customer to another 
#.....and depends on subsribed services. It simply shows that revenue is predicated on available services but varied in terms of customer's 
#.....profiles as shown, with a customer generating 24.96 monthly charges, while another is generating 44.92.