#### TASK 1 - The Business Scenario For FreshWave Telecom, Using Its Historical Customer Data For Three Separate Business
#### Questions From Three Different Teams - The Finance Team, The Retention Team, The Marketing Team, Using A SINGLE DATASET

#### IDEA - To View The Retention Team Of FreshWave Telecom As A Separate Client With The Brief Deserving A Well Focused And 
####        Separate Attention And Report To Meet The Requirements Of The Business Challenge And The Expected Solution

#### Scenario 2 - The Business Concern And Request Of The Retention Team About Customers Cancelling Their Subscriptions And
#### Finding A Way To Identify And Flag Those Likely To Churn So They Can Be Contacted Proactively.

#### Addressing Scenario 2: Predicting Customer Churn, Preparing And Presenting The Findings As A Portfolio Project To The
#### Retention Team

#### TASK 2 - Getting The Dataset From Kaggle

#### Importing Important Libraries

In [197]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Importing The Dataset

In [198]:
 TelcoCustomers = pd.read_csv("C:/Users/Mummy Utee/Downloads/TelcoCustomers/Telco_Customers_Churn.csv")

In [199]:
TelcoCustomers.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [200]:
TelcoCustomers

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

#### TASKS - NO 3

#####  DATA PREPARATION

##### STEP 1 - EXPLORING THE DATA SET TO GET IT INTO SHAPE FOR A MODEL

In [201]:
TelcoCustomers.shape

(7043, 21)

##### Displaying the 21 Columns To Identify Relevant Columns For The Task And Request From The Retention Team To Know Ahead
##### Of Time, Which Customers Are Likely To Cancel Their Service (The Churn Column)

In [202]:
TelcoCustomers.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

##### Checking For Missing Values And Data Types

In [203]:
TelcoCustomers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [204]:
# TotalCharges column has numeric values but data type is not int64 or float64 as expected for building a moder but object.

TelcoCustomers['TotalCharges'].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

##### Checking For Null Values Within The Rows

In [205]:
TelcoCustomers.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [206]:
# No null values detected or observed with the 0 outcome above, in the 7043 rows of the 21 columns.

##### Observations Of The Data Types, For Necessary Data Cleaning Of Relevant Columns

In [207]:
# 1. Numerical Columns - Senior Citizen (int64), tenure (int64), Monthly Charges (float64), Total Charges (object) instead of int or float
#... Total Charges column with object data type indicates that some values are strings as either blank spaces or hypen (-) that needs to be 
#... converted to either integer or float..... after confirming whichever is the case,to determine the method of conversion of the object data type, 
#... using either astype(int), mean (average) or median, otherwise use pd.numeric and coerce errors, to NaN, then replace with

#... needs to be converted to either integer or float.

# 2. Categorical Columns - Other Columns have object data type because they are text and strings.

# 3. No missing row(s) observed or seen from the above as confirmed with all non-null count of the 7043 rows.
#... Columns total number is shown as 21 and total number of rows is from 0 - 7042 totalling 7043.

# 4. The data shape also confirms 7043 rows and 21 columns

##### Creating A Copy Of The Data Set For The Necessary Changes Of Data Types To Preserve The Original Dataset

In [208]:
TelcoCustomers_Copy = TelcoCustomers

TelcoCustomers_Copy = TelcoCustomers.copy()

In [209]:
TelcoCustomers_Copy

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

##### Converting Total Charges (Object) Column To Integer Or Float For Data Cleaning And Preparation

In [210]:
#  Checking For The Actual Values In All The Rows Of TotalCharges With Numerical Values But Showing Object Data Type To 
#  Establish The Conversion Method To Use By Filtering The Column To See The Rows As Either Hypen, Text/Strings Or Blank

In [211]:
Filter = TelcoCustomers_Copy['TotalCharges']== ' '

In [212]:
TelcoCustomers_Copy[Filter]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [213]:
TelcoCustomers_Copy[Filter].value_counts

<bound method DataFrame.value_counts of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0
753   3115-CZMZD    Male              0      No        Yes       0
936   5709-LVOEQ  Female              0     Yes        Yes       0
1082  4367-NUYAO    Male              0     Yes        Yes       0
1340  1371-DWPAZ  Female              0     Yes        Yes       0
3331  7644-OMVMY    Male              0     Yes        Yes       0
3826  3213-VVOLG    Male              0     Yes        Yes       0
4380  2520-SGTTA  Female              0     Yes        Yes       0
5218  2923-ARZLG    Male              0     Yes        Yes       0
6670  4075-WKNIU  Female              0     Yes        Yes       0
6754  2775-SEFEE    Male              0      No        Yes       0

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ...
753           Yes                No              No  No internet service  ...
936           Yes                No             DSL                  Yes  ...
1082          Yes               Yes              No  No internet service  ...
1340           No  No phone service             DSL                  Yes  ...
3331          Yes                No              No  No internet service  ...
3826          Yes               Yes              No  No internet service  ...
4380          Yes                No              No  No internet service  ...
5218          Yes                No              No  No internet service  ...
6670          Yes               Yes             DSL                   No  ...
6754          Yes               Yes             DSL                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
488                   Yes                  Yes                  Yes
753   No internet service  No internet service  No internet service
936                   Yes                   No                  Yes
1082  No internet service  No internet service  No internet service
1340                  Yes                  Yes                  Yes
3331  No internet service  No internet service  No internet service
3826  No internet service  No internet service  No internet service
4380  No internet service  No internet service  No internet service
5218  No internet service  No internet service  No internet service
6670                  Yes                  Yes                  Yes
6754                   No                  Yes                   No

          StreamingMovies  Contract PaperlessBilling  \
488                    No  Two year              Yes
753   No internet service  Two year               No
936                   Yes  Two year               No
1082  No internet service  Two year               No
1340                   No  Two year               No
3331  No internet service  Two year               No
3826  No internet service  Two year               No
4380  No internet service  Two year               No
5218  No internet service  One year              Yes
6670                   No  Two year               No
6754                   No  Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
488   Bank transfer (automatic)          52.55                  No
753                Mailed check          20.25                  No
936                Mailed check          80.85                  No
1082               Mailed check          25.75                  No
1340    Credit card (automatic)          56.05                  No
3331               Mailed check          19.85                  No
3826               Mailed check          25.35                  No
4380               Mailed check          20.00                  No
5218               Mailed check          19.70                  No
6670               Mailed check          73.35                  No
6754  Bank transfer (automatic)          61.90                  No

[11 rows x 21 columns]>

##### Observations Of The Outcome Of The Filtered Total Charges Column And Other Columns Based On Value Counts
##### For Insights About The Blank Rows That Created The Object Data Type

In [214]:
# 1. The 'TotalCharges' column, after it was filtered, showed 11 customers with blank rows, but with subscription details in the other 
#....columns, except the 'tenure' column with 0.

# 2. The value count of the filtered 'TotalCharges' column also showed the 'tenure' column without any previous tenure of services from  
#....the company.This gives an indication that the 11 blank rows are for new customers who had just subscribed for the services of the 
#....company and therefore had not yet recorded any used tenure, unlike the rest of the customers.

# 3. This also provides a guide as to the type of applicable conversion method... Using mean average or median does not apply
#....to blank spaces since there are no values. 

# 4. Conversion to integer with '.astype(int) gave ValueError'invalid literal for (int) with base 10:'29.85'). Converting the column 
#....did not work because of the 11 rows with blank spaces on the 'TotalCharges' column. 

# 5. The possible method to try therefore is to have the blank spaces changed to numeric values, with 'pd.to_numeric' code to give 
#....the 11 rows NaN values and then replace them with 0 values, with the 'fillna' code as float.

#####  Changing The Blank Spaces To NaN Before Replacing The NaN With Null Values

In [215]:
TelcoCustomers_Copy['TotalCharges'] = pd.to_numeric(TelcoCustomers_Copy['TotalCharges'], errors = 'coerce')

#####  Checking To See The New And Changed Data Type Of TotalCharges Column

In [216]:
TelcoCustomers_Copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

##### Observations Of The TotalCharges Column After Changing The vData Type To Float64

In [217]:
# 1. The data type has been effectively changed from object to float64

# 2. The rows of TotalCharges column has reduced from 7043 to 7032, which indicates null values for the 11 rows with blank spaces 
#....are excluded that still need to be converted from NaN to float64 to have the complete 7043 rows converted to float64.

##### Checking To Confirm The Null Values Are The 11 rows Of Blank Spaces Changed To NaN

In [218]:
TelcoCustomers_Copy.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

##### Replacing The Null Values Of The II Rows With 0 To Have Non-Null Values

In [219]:
TelcoCustomers_Copy['TotalCharges'] = TelcoCustomers_Copy['TotalCharges'].fillna(0)

In [220]:
TelcoCustomers_Copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [221]:
TelcoCustomers_Copy.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [222]:
# Observation Of Total Charges Column After The Final Conversion

# 1. Total Charges column now has complete 7043 rows with no blank spaces or null values again 

# 2. Total Charges column is now showing 0, and has become non-null like the other columns

# 3. Total Charges Column has also been fully converted from object to float64 to prepare the data set for building a model.

##### Checking The Data Set For Final Preparation To Get It Fully Ready For The Model

In [223]:
TelcoCustomers_Copy

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [224]:
TelcoCustomers_Copy.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [225]:
TelcoCustomers_Copy.describe # The descriptive informaton shows both categorical and integer/float64 columns requiring actions

<bound method NDFrame.describe of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95       1889.50
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80       1990.50
7039              Yes    Credit card (automatic)         103.20       7362.90
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40        306.60
7042              Yes  Bank transfer (automatic)         105.65       6844.50

      Churn
0        No
1        No
2       Yes
3        No
4       Yes
...     ...
7038     No
7039     No
7040     No
7041    Yes
7042     No

[7043 rows x 21 columns]>

#####  Checking The Unique Values Of All Columns To Determine Those To Drop For, To Know Customers That Are Likely To Cancel
##### Their Service, Based On Their Profile And The Services They Signed For, As Requested By The Retention Team

In [226]:
#   This column provides the identity of customers and very useful for identifying customers and their behaviour for a likely 
#...churn decision, to reach out them proactively.

TelcoCustomers_Copy['customerID'].unique()

array(['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', ..., '4801-JZAZL',
       '8361-LTMKD', '3186-AJIEK'], dtype=object)

In [227]:
# This column shows a binary categorical value for a classification model and simply requires simple encoding.
 
TelcoCustomers_Copy['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [228]:
TelcoCustomers_Copy['SeniorCitizen'].unique() # A combination Of old & new customers with the old billed, and new not billed yet.

array([0, 1])

In [229]:
TelcoCustomers_Copy['SeniorCitizen'].value_counts(normalize=True).round(2) # 84% new customers have no charges yet. Only 16% billed

SeniorCitizen
0    0.84
1    0.16
Name: proportion, dtype: float64

In [230]:
TelcoCustomers_Copy['SeniorCitizen'].value_counts()     # 5901 are new customers with no charges yet. 1142 are old and billed

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [231]:
TelcoCustomers_Copy['Partner'].unique()      #  They are customers/subscribers with special identification

array(['Yes', 'No'], dtype=object)

In [232]:
TelcoCustomers_Copy['Partner'].value_counts()    # More than half of the customers/subscribers are Partners. This is useful.

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [233]:
TelcoCustomers_Copy['Partner'].value_counts(normalize=True).round(2)   # They are special and committed customers/subscribers

Partner
No     0.52
Yes    0.48
Name: proportion, dtype: float64

In [234]:
TelcoCustomers_Copy['Dependents'].unique()    # This gives a useful and additional information about the customer subscription

array(['No', 'Yes'], dtype=object)

In [235]:
TelcoCustomers_Copy['tenure'].unique()    # This is important for proactive action on customers likely to churn

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [236]:
#   This gives informative values on the proportion of each customer's tenure on the total tenure of all customers..
 
TelcoCustomers_Copy['tenure'].value_counts(normalize=True).round(2)

tenure
1     0.09
72    0.05
2     0.03
3     0.03
4     0.02
      ...
28    0.01
39    0.01
44    0.01
36    0.01
0     0.00
Name: proportion, Length: 73, dtype: float64

In [237]:
TelcoCustomers_Copy['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [238]:
TelcoCustomers_Copy['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [239]:
TelcoCustomers_Copy['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [240]:
TelcoCustomers_Copy['OnlineSecurity'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [241]:
TelcoCustomers_Copy['OnlineBackup'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [242]:
TelcoCustomers_Copy['DeviceProtection'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [243]:
TelcoCustomers_Copy['TechSupport'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [244]:
TelcoCustomers_Copy['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [245]:
TelcoCustomers_Copy['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [246]:
TelcoCustomers_Copy['Contract'].unique() # The Different types of contract subscribed to by customers

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [247]:
TelcoCustomers_Copy['Contract'].value_counts()    # Shows types of contract, no of actual contract and duration of contract

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [248]:
TelcoCustomers_Copy['Contract'].value_counts(normalize=True).round(2)      # % of The different types of contract

Contract
Month-to-month    0.55
Two year          0.24
One year          0.21
Name: proportion, dtype: float64

In [249]:
TelcoCustomers_Copy['PaperlessBilling'].unique()

array(['Yes', 'No'], dtype=object)

In [250]:
TelcoCustomers_Copy['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [251]:
TelcoCustomers_Copy['MonthlyCharges'].unique()    # Total Charges Covers Monthly Charges Based On TENURE/CONTRACT

array([29.85, 56.95, 53.85, ..., 63.1 , 44.2 , 78.7 ])

In [252]:
TelcoCustomers_Copy['TotalCharges'].unique()

array([  29.85, 1889.5 ,  108.15, ...,  346.45,  306.6 , 6844.5 ])

In [253]:
TelcoCustomers_Copy['Churn'].unique()   # This indicates active customers(No) & those intending to stop services(Yes)

array(['No', 'Yes'], dtype=object)

In [254]:
TelcoCustomers_Copy['Churn'].value_counts() # Shows number of active customers to continue subscription (No) & Number likely to stop (Yes)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [255]:
TelcoCustomers_Copy['Churn'].value_counts(normalize=True).round(2) # Indicates 73% to stay active, 27% intending to stop services

Churn
No     0.73
Yes    0.27
Name: proportion, dtype: float64

#####  Analysis Of The DataSet From The Unique Values To Determine The Columns To Drop, Features And Target Columns

In [256]:
# 1. The Dataset provides historical information about customer's profile to identify them, the services subscribed to, for
#... billing, the service contract, monthly charges which translate into monthly payment and cummulates as total charges. 
#... A customer's profile and subscribed services is therefore the basis and determinig features for monthly billing and 
#... invariably monthly charges as long as the customer does not churn and the services signed up continue.

# 2. TO DROP GENDER COLUMN

#... The column is not really relevant or needed because the gender of customers does not matter and has no effect 
#... or nothing to do with identifying customers that are likely to churn. It can be useful fo a different purpose. 

# 3. CUSTOMER PROFILE AND SUBSCRIBED SERVICES COLUMNS FOR BILLING AND PAYMENTS ARE THE FEATURES... 
#....REASONING AND JUSTIFICATION

# a. The columns for customer's profile and subscribed services with ID column are all useful as features columns and relevant
#... for studying a customer's behaviour to establish those likely to churn. 
#... The profile and billing features columns with int64/float64 are observed to have continuous values, and requires the decision
#... tree classifier algorithm, considered appropriated because the target column is 'churn't, with categorical values to predict 
#... the decision of Telco customers, to continue subscribing to the current services, with or without additional nes services, or
#... decide to churn, for testing and training the decision tree classifier model for predicting a likely churn decision for
#... necessary proactive action and reach out to such customers ahead of tenure expiration for customer retention plans. 

# b. The binary features columns with Yes/No values need to be encoded, using map.apply to convert them to 0,1. 
# c. The other categorical features columns with a combination of mixed multiple texts and numerrical values, need to be encoded 
#... to 0,1 using One-HotEncoder, whiich is suitable and appropriate for features columns to make them readable for the decision tree 
#....model to learn and predict likely churn customers as requested by the Retention Team.

# 4. TOTAl CHARGES IS CONSIDERED APPROPRIATE TO BE PART OF FEATURES FOR THIS BUSINESS REQUEST. 
#... REASONING AND JUSTIFICATION

# a. The historical customer profile,'tenure' and 'contract' records which ddetermine monthly revenue (monthly charges), based on
#... applicable subscribed monthly services only. A way to know customers considering a likey churn decision, which will affect
#... 'monthly' and cumulatively 'totalcharges' makes it unnecessary to keep 'monthly charges' as features to avoid duplication,
#...  so there is no data leakage in the decision tree classifier model, especially since 'Monthly charges' do not apply to all 
#...  available services, but to only the subscribed services because 'tenure' and 'contract' do not evenly apply or recur monthly 
#...  for all customers and give that monthly charges is actual current charges, while total charges
#... is the cumullative billing of customers.


# 5. TO DROP GENDER COLUMN ... REASONING AND JUSTIFICATION

# a..The gender column simply gives personal identity of customers as either male or female and has nothing to do with a customer's
#....decision to churn or not churn.

#    TO DROP MONTHLY CHARGES ... REASONING AND JUSTIFICATION

# b  Monthly charges is better dropped since, the values include billing that cumulates in total charges, that is like duplicating the
#... values already in total charges which can result in data leakage in the model and cause a misleading outcome, given the relationship
#... with total charges that also involves and includes'tenure' and 'contract', despite being historical.

#... The column is not necessary as it does not give a full overview of total customer tenure and contract details.


# 6. USEFUL CUSTOMER INFORMATION FOR DATA CLEANING FOR THE DECISION TREE CLASSIFIER MODEL

# b  The data information about the 11 rows with blank spaces in 'total charges' column, due to 0 values on 'tenure; and 'senior citizens', 
#... is an indicatation that the rows are for new customers and subscribers, who do not yet have historical billing and charges, hence 0.
# c  The 'total charges' column as part of features is considered important because it is closely related to both 'tenure' and 'monthly charges' 
#....with the cummulative values shown in the dataset. 
# d  The column is also better as features since, including it in the features columns could result in some data leakage in the model and cause
#....a misleading outcome, given that its relationship with 'tenure' is historical rather than the required knowledge ahead of time, about 
#... customers that are likely to cancel their service, either partially or fully.
# e. The basis for 'monthly charges' is just the sevices subscribed to in a month even though contact type may not be monthly and 
#....customers 'tenure' may also vary from month to month. Actual 'monthly charges' is therefore different from 'total charges'. 
# f  All the considerations above, logically require that 'monthly charges' column be excluded and dropped from the predictive features columns 
#....required for buiding the model for the Retention Team report. 


# 7. TO USE THE CHURN COLUMN AS TARGET ... REASONING AND JUSTIFICATION

#... This column is considered the target colum because it is indicative of a customer's likely decision to cancel or stop subscribing for 
#... services either outrightly or partially in the nearest future, for which the Retention Team requires a predictive information ahead of 
#... for necessary proctive steps and actions.
#... The churn indication and situation is futuristic and can be predicted using the decision tree clssifier algorithm model to establish 
#... an accurate, reliable and consistent information in the report to the Retention team using relevant evaluation metrics of the model.

##### Dropping Columns Not Needed To identify Customers That Are Likely To Cancel Services, Based On Their
##### Profile And The Services They Signed Up For, As Required By The Retention Team Using The Decision Tree Classifier Model

In [257]:
TelcoCustomers_Copy = TelcoCustomers_Copy.drop(columns=['gender','MonthlyCharges'])

##### Checking To Confirm The Columns Listed Are Dropped

In [258]:
print(TelcoCustomers_Copy.columns.tolist())

['customerID', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

In [259]:
TelcoCustomers_Copy.columns

Index(['customerID', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'TotalCharges', 'Churn'],
      dtype='object')

##### Encoding Categorical Features Customer Profile And Services Columns With Binary Values Using Mapping

In [260]:
TelcoCustomers_Copy['Partner'] = TelcoCustomers_Copy['Partner'].map({'No': 0, 'Yes': 1})
TelcoCustomers_Copy['Dependents'] = TelcoCustomers_Copy['Dependents'].map({'No': 0, 'Yes': 1})
TelcoCustomers_Copy['PhoneService'] = TelcoCustomers_Copy['PhoneService'].map({'No': 0, 'Yes': 1})
TelcoCustomers_Copy['PaperlessBilling'] = TelcoCustomers_Copy['PaperlessBilling'].map({'No': 0, 'Yes': 1})

##### Checking To Confirm Encoding Of The Binary Features Values

In [261]:
TelcoCustomers_Copy

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
0,7590-VHVEG,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,No
1,5575-GNVDE,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,1889.50,No
2,3668-QPYBK,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,108.15,Yes
3,7795-CFOCW,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),1840.75,No
4,9237-HQITU,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,1,1,24,1,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,1,Mailed check,1990.50,No
7039,2234-XADUH,0,1,1,72,1,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,1,Credit card (automatic),7362.90,No
7040,4801-JZAZL,0,1,1,11,0,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,1,Electronic check,346.45,No
7041,8361-LTMKD,1,1,0,4,1,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Mailed check,306.60,Yes
7042,3186-AJIEK,0,0,0,66,1,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),6844.50,No

In [262]:
TelcoCustomers_Copy.columns

Index(['customerID', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'TotalCharges', 'Churn'],
      dtype='object')

##### Separating The Dataset Into Features And Target

In [263]:
X = ['customerID', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod','TotalCharges']

Y = ['Churn']

In [264]:
Features = X
Target = Y

X = Features
Y = Target

X = TelcoCustomers_Copy.drop(columns=['Churn'])   # Features
Y = TelcoCustomers_Copy['Churn']                   # Target

##### Splitting The Dataset Into Training And Testing Sets Before Encoding As Appropriate

In [265]:
from sklearn.model_selection import train_test_split

In [266]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [267]:
X_train

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges
2142,4223-BKEOR,0,0,1,21,1,No,DSL,Yes,No,Yes,No,No,Yes,One year,0,Mailed check,1336.80
1623,6035-RIIOM,0,0,0,54,1,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Two year,1,Bank transfer (automatic),5129.45
6074,3797-VTIDR,0,1,0,1,0,No phone service,DSL,No,No,No,No,No,No,Month-to-month,1,Electronic check,23.45
1362,2568-BRGYX,0,0,0,4,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,237.95
6754,2775-SEFEE,0,0,1,0,1,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,1,Bank transfer (automatic),0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,0684-AOSIH,0,1,0,1,1,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,1,Electronic check,95.00
5191,5982-PSMKW,0,1,1,23,1,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,1,Credit card (automatic),2198.30
5226,8044-BGWPI,0,1,1,12,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,1,Electronic check,306.05
5390,7450-NWRTR,1,0,0,12,1,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,1,Electronic check,1200.15
860,4795-UXVCJ,0,0,0,26,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,0,Credit card (automatic),457.30

In [268]:
X_test

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges
185,1024-GUALD,0,1,0,1,0,No phone service,DSL,No,No,No,No,No,No,Month-to-month,1,Electronic check,24.80
2715,0484-JPBRU,0,0,0,41,1,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,1,Bank transfer (automatic),996.45
3825,3620-EHIMZ,0,1,1,52,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,0,Mailed check,1031.70
1807,6910-HADCM,0,0,0,1,1,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,0,Electronic check,76.35
132,8587-XYZSF,0,0,0,67,1,No,DSL,No,No,No,Yes,No,No,Two year,0,Bank transfer (automatic),3260.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,2845-KDHVX,0,1,0,64,1,No,DSL,No,Yes,Yes,Yes,No,Yes,Two year,1,Mailed check,4378.80
315,5027-YOCXN,0,1,1,51,1,Yes,Fiber optic,Yes,Yes,No,Yes,Yes,Yes,One year,0,Credit card (automatic),5686.40
2439,8884-MRNSU,0,1,1,17,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,0,Bank transfer (automatic),329.75
5002,0567-XRHCU,0,1,1,69,0,No phone service,DSL,Yes,No,Yes,No,No,Yes,Two year,1,Credit card (automatic),2960.10
1161,5868-CZJDR,0,0,1,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Mailed check,31.35

In [269]:
Y_train

2142     No
1623     No
6074    Yes
1362    Yes
6754     No
       ...
3772    Yes
5191     No
5226     No
5390    Yes
860      No
Name: Churn, Length: 5634, dtype: object

In [270]:
Y_test

185     Yes
2715     No
3825     No
1807    Yes
132      No
       ...
6366     No
315      No
2439     No
5002     No
1161    Yes
Name: Churn, Length: 1409, dtype: object

##### Checking The Shape Of The Training And Test Sets Split

In [173]:
print(f'Training Set:{X_train.shape}')
print(f'Testing Set:{X_test.shape}')

Training Set:(5634, 18)
Testing Set:(1409, 18)

##### Encoding The remaining Categorical Features Columns With Multiple Combination Of Text And Numerical Values Using One-HotEncoder 
##### Since The Columns Are Features To Covert The Values To Binary

In [174]:
# Defining The Categorical Columns With Multiple Text And Numerical Values

Categorical_Columns = ['customerID','MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaymentMethod']

In [175]:
from sklearn .preprocessing import OneHotEncoder

##### Creating An Instance Of OneHotEncoder Using Dummy ('First' Is Used To Avoid Creating a Redundant Variable For Each Category)

In [176]:
Encode = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)

##### Fitting Only Categorical Columns With Multiple Text And Binary Values, Excluding THe Already Numeric Binary Values Columns

In [177]:
# Fitting On Only Categorical Columns Of X_train And Transforming X_test

X_train_Encoded = Encode.fit_transform(X_train[Categorical_Columns])
X_test_Encoded = Encode.transform(X_test[Categorical_Columns])

In [178]:
X_train_Encoded

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [179]:
X_train_Encoded.shape

(5634, 5665)

In [180]:
X_test_Encoded

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [181]:
X_test_Encoded.shape

(1409, 5665)

In [182]:
print(Categorical_Columns)

['customerID', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

In [183]:
print('Number of categorical columns:', len(Categorical_Columns))

Number of categorical columns: 11

In [184]:
print (X_train[Categorical_Columns].shape)

(5634, 11)

In [185]:
print(X_test[Categorical_Columns].shape)

(1409, 11)

#####  Analysis Of Obsevations On The Encoded Columns

In [186]:
# Observations And Reasoning On The OneHotEncoder And Mapping Conversion Of Categorical Columns To Numeric

# 1. The encoding actions only focused on the remaining categorical features columns with the combined text and binary values.
# 2. Those categorical columns are with OneHotEncoder, applied only on features columns, converted to numeric. 
# 3. These columns are now named X_train_Encoded

# Observaytions Of The Mapping On The Binary Columns (yes/No) 

# 1. Only a few binary columns were converted to numeric.
# 2. Those binary-numeric columns were excluded from the OneHotEncoding action and effects.
# 3. These columns are still X-train

# Implications Of The Separate Actions

# 1. The features columns, though already converted to numeric, with separated and different applications of convertion 
#....methods are now X-train and X_train_encoded
# 2. This separate features (X) columns of categorical numeric-binary (X_train) and categorical numeric-multiple text/binary
#....(X_train_Encoded and need to be merged together to have a single features for training and testing of equal rows as 
#....Y_train and Y_test. 

#  Required Actions

# 1. To merge the entire categorical mapped binary features columns with the encoded text and binary features columns, all 
#....converted to numeric, and have a combined and single numeric features columns required to complete the data preprocessing 
#....and preparation for building a model for the Retention team to know ahead of time, which customers are likely to cancel 
#... their service (The Churn Column)

#####  Combining the Numeric Binary Columns And Numeric Categorical Encoded Columns

#####  1 - Converting The Encoded Values (Arrays) To DataFrames To Be Able To Combine Them With The Numeric And Binary_Mapped
#####      And Encoded Columns As A Single Features Columns

In [187]:
X_train_Encoded = pd.DataFrame(X_train_Encoded, columns=Encode.get_feature_names_out(Categorical_Columns), index=X_train.index)
X_test_Encoded = pd.DataFrame(X_test_Encoded, columns=Encode.get_feature_names_out(Categorical_Columns), index=X_test.index)

##### 2 - Listing And Identifying The Numeric And Binary-Mapped Encoded Columns Still Reflected As X_Train

In [188]:
X_train_Numeric = [Columns for Columns in X_train if Columns not in Categorical_Columns]
X_test_Numeric = [Columns for Columns in X_test if Columns not in Categorical_Columns]

##### 3 - Combining X_train (Numerical int64/float64 Columns And Numerical Binary-Mapped Columns) With The Encoded Multiple
#####     Categorical Text And Binary Values, To Have A Complete Single Features Columns For The Model For Both Training And
#####     Testing Sets Using pd.concat( ) As A Better Application Than Using Concat

In [189]:
X_train_Combined = pd.concat([X_train[X_train_Numeric], X_train_Encoded], axis = 1)

In [190]:
X_test_Combined = pd.concat([X_test[X_test_Numeric], X_test_Encoded], axis = 1)

In [191]:
print(X_train_Combined.shape)

(5634, 5672)

In [192]:
print(X_test_Combined.shape)

(1409, 5672)

In [193]:
print(X_train_Combined.columns.tolist())

['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'PaperlessBilling', 'TotalCharges', 'customerID_0002-ORFBO', 'customerID_0003-MKNFE', 'customerID_0004-TLHLJ', 'customerID_0011-IGKFF', 'customerID_0013-EXCHZ', 'customerID_0013-MHZWF', 'customerID_0013-SMEOE', 'customerID_0014-BMAQU', 'customerID_0015-UOCOJ', 'customerID_0017-DINOC', 'customerID_0017-IUDMW', 'customerID_0019-EFAEP', 'customerID_0019-GFNTW', 'customerID_0020-INWCK', 'customerID_0021-IKXGC', 'customerID_0022-TCJCI', 'customerID_0023-HGHWL', 'customerID_0023-XUOPT', 'customerID_0027-KWYKW', 'customerID_0030-FNXPP', 'customerID_0031-PVLZI', 'customerID_0032-PGELS', 'customerID_0036-IHMOT', 'customerID_0040-HALCW', 'customerID_0042-JVWOJ', 'customerID_0042-RLHYP', 'customerID_0048-LUMLS', 'customerID_0052-DCKON', 'customerID_0052-YNYOT', 'customerID_0056-EPFBG', 'customerID_0057-QBUQH', 'customerID_0058-EVZWM', 'customerID_0060-FUALY', 'customerID_0064-SUDOG', 'customerID_0064-YIJGF', 'customerID_0067-DKWBL', 'customerID_0068-FIGTF', 'customerID_0071-NDAFP', 'customerID_0074-HDKDG', 'customerID_0082-LDZUE', 'customerID_0082-OQIQY', 'customerID_0083-PIVIK', 'customerID_0089-IIQKO', 'customerID_0093-EXYQL', 'customerID_0093-XWZFY', 'customerID_0094-OIFMO', 'customerID_0096-FCPUF', 'customerID_0098-BOWSO', 'customerID_0100-DUVFC', 'customerID_0103-CSITQ', 'customerID_0104-PPXDV', 'customerID_0106-UGRDO', 'customerID_0107-YHINA', 'customerID_0111-KLBQG', 'customerID_0112-QAWRZ', 'customerID_0112-QWPNC', 'customerID_0114-IGABW', 'customerID_0114-PEGZZ', 'customerID_0114-RSRRW', 'customerID_0115-TFERT', 'customerID_0117-LFRMW', 'customerID_0121-SNYRK', 'customerID_0125-LZQXK', 'customerID_0128-MKWSG', 'customerID_0129-KPTWJ', 'customerID_0130-SXOUN', 'customerID_0133-BMFZO', 'customerID_0134-XWXCE', 'customerID_0136-IFMYD', 'customerID_0137-OCGAB', 'customerID_0137-UDEUO', 'customerID_0139-IVFJG', 'customerID_0141-YEAYS', 'customerID_0142-GVYSN', 'customerID_0151-ONTOV', 'customerID_0156-FVPTA', 'customerID_0164-APGRB', 'customerID_0164-XAIRP', 'customerID_0168-XZKBB', 'customerID_0174-QRVVY', 'customerID_0177-PXBAT', 'customerID_0178-CIIKR', 'customerID_0178-SZBHO', 'customerID_0181-RITDD', 'customerID_0186-CAERR', 'customerID_0187-QSXOE', 'customerID_0191-EQUUH', 'customerID_0191-ZHSKZ', 'customerID_0193-ESZXP', 'customerID_0195-IESCP', 'customerID_0196-JTUQI', 'customerID_0196-VULGZ', 'customerID_0197-PNKNK', 'customerID_0201-OAMXR', 'customerID_0203-HHYIJ', 'customerID_0206-OYVOC', 'customerID_0206-TBWLC', 'customerID_0207-MDKNV', 'customerID_0214-JHPFW', 'customerID_0215-BQKGS', 'customerID_0218-QNVAS', 'customerID_0219-QAERP', 'customerID_0219-YTZUE', 'customerID_0221-NAUXK', 'customerID_0224-HJAPT', 'customerID_0224-NIJLP', 'customerID_0224-RLWWD', 'customerID_0225-ZORZP', 'customerID_0228-MAUWC', 'customerID_0230-UBYPQ', 'customerID_0231-LXVAP', 'customerID_0233-FTHAV', 'customerID_0234-TEVTT', 'customerID_0235-KGSLC', 'customerID_0236-HFWSV', 'customerID_0237-YFUTL', 'customerID_0238-WHBIQ', 'customerID_0239-OXEXL', 'customerID_0244-LGNFY', 'customerID_0247-SLUJI', 'customerID_0248-IPDFW', 'customerID_0248-PGHBZ', 'customerID_0253-ZTEOB', 'customerID_0254-KCJGT', 'customerID_0254-WWRKD', 'customerID_0256-LTHVJ', 'customerID_0257-KXZGU', 'customerID_0258-NOKBL', 'customerID_0260-ZDLGK', 'customerID_0263-FJTQO', 'customerID_0264-CNITK', 'customerID_0265-EDXBD', 'customerID_0265-PSUAE', 'customerID_0266-CLZKZ', 'customerID_0266-GMEAO', 'customerID_0268-QKIWO', 'customerID_0269-XFESX', 'customerID_0270-THENM', 'customerID_0274-JKUJR', 'customerID_0277-BKSQP', 'customerID_0277-ORXQS', 'customerID_0278-YXOOG', 'customerID_0280-XJGEX', 'customerID_0281-CNTZX', 'customerID_0282-NVSJS', 'customerID_0285-INHLN', 'customerID_0292-WEGCH', 'customerID_0295-PPHDO', 'customerID_0295-QVKPB', 'customerID_0298-XACET', 'customerID_0301-FIDRB', 'customerID_0301-KOBTQ', 'customerID_0302-JOIVN', 'customerID_0303-UNCIP', 'customerID_0305-SQECB', 'customerID_0307-BCOPK', 'customerID_0308-GIQJT', 'customerID_0308-IVGOK', 'customerID_0310-SUCIN', 'customerID_0310-VQXAM', 'customerID_0311-QYWSS', 'customerID_0314-TKOSI', 'customerID_0315-LVCRK', 'customerID_0318-QUUOB', 'customerID_0319-QZTCO', 'customerID_0320-DWVTU', 'customerID_0320-JDNQG', 'customerID_0322-CHQRU', 'customerID_0323-XWWTN', 'customerID_0324-BRPCJ', 'customerID_0325-XBFAC', 'customerID_0326-VDYXE', 'customerID_0327-WFZSY', 'customerID_0336-KXKFK', 'customerID_0336-PIKEI', 'customerID_0337-CNPZE', 'customerID_0343-QLUZP', 'customerID_0345-HKJVM', 'customerID_0345-XMMUG', 'customerID_0347-UBKUZ', 'customerID_0348-SDKOL', 'customerID_0354-WYROK', 'customerID_0356-OBMAC', 'customerID_0357-NVCRI', 'customerID_0362-RAOQO', 'customerID_0362-ZBZWJ', 'customerID_0363-QJVFX', 'customerID_0363-SVHYR', 'customerID_0365-BZUWY', 'customerID_0365-GXEZS', 'customerID_0365-TRTPY', 'customerID_0366-NQSHS', 'customerID_0373-AIVNJ', 'customerID_0374-AACSZ', 'customerID_0374-IOEGQ', 'customerID_0376-OIWME', 'customerID_0376-YMCJC', 'customerID_0377-JBKKT', 'customerID_0378-CJKPV', 'customerID_0378-NHQXU', 'customerID_0378-TOVMS', 'customerID_0378-XSZPU', 'customerID_0380-NEAVX', 'customerID_0380-ZCSBI', 'customerID_0383-CLDDA', 'customerID_0384-LPITE', 'customerID_0384-RVBPI', 'customerID_0386-CWRGM', 'customerID_0388-EOPEX', 'customerID_0390-DCFDQ', 'customerID_0392-BZIUW', 'customerID_0394-YONDK', 'customerID_0396-YCHWO', 'customerID_0397-GZBBC', 'customerID_0401-WDBXM', 'customerID_0402-CQAJN', 'customerID_0402-OAMEN', 'customerID_0404-AHASP', 'customerID_0406-BPDVR', 'customerID_0407-BDJKB', 'customerID_0411-EZJZE', 'customerID_0415-MOSGF', 'customerID_0420-BWTPW', 'customerID_0420-HLGXF', 'customerID_0420-TXVSG', 'customerID_0422-OHQHQ', 'customerID_0422-UXFAP', 'customerID_0423-UDIJQ', 'customerID_0426-TIRNE', 'customerID_0428-AXXLJ', 'customerID_0428-IKYCP', 'customerID_0430-IHCDJ', 'customerID_0431-APWVY', 'customerID_0432-CAJZV', 'customerID_0434-CSFON', 'customerID_0436-TWFFZ', 'customerID_0439-IFYUN', 'customerID_0440-EKDCF', 'customerID_0440-MOGPM', 'customerID_0440-QEXBZ', 'customerID_0440-UEDAI', 'customerID_0442-TDYUO', 'customerID_0442-ZXKVS', 'customerID_0447-BEMNG', 'customerID_0447-RXSGD', 'customerID_0454-OKRCT', 'customerID_0455-ENTCR', 'customerID_0458-HEUZG', 'customerID_0461-CVKMU', 'customerID_0463-WZZKO', 'customerID_0463-ZSDNT', 'customerID_0464-WJTKO', 'customerID_0468-YRPXN', 'customerID_0471-ARVMX', 'customerID_0471-LVHGK', 'customerID_0475-RIJEP', 'customerID_0480-BIXDE', 'customerID_0480-KYJVA', 'customerID_0481-SUMCB', 'customerID_0484-FFVBJ', 'customerID_0485-ZBSLN', 'customerID_0486-HECZI', 'customerID_0486-LGCCH', 'customerID_0487-CRLZF', 'customerID_0487-RPVUM', 'customerID_0487-VVUVK', 'customerID_0488-GSLFR', 'customerID_0491-KAPQG', 'customerID_0495-RVCBF', 'customerID_0495-ZBNGW', 'customerID_0496-AHOOK', 'customerID_0504-HHAPI', 'customerID_0505-SPOOW', 'customerID_0506-LVNGN', 'customerID_0506-YLVKJ', 'customerID_0508-OOLTO', 'customerID_0508-SQWPL', 'customerID_0513-RBGPE', 'customerID_0515-YPMCW', 'customerID_0516-OOHAR', 'customerID_0516-QREYC', 'customerID_0516-UXRMT', 'customerID_0516-VRYBW', 'customerID_0519-DRGTI', 'customerID_0519-XUZJU', 'customerID_0520-FDVVT', 'customerID_0526-SXDJP', 'customerID_0531-XBKMM', 'customerID_0531-ZZJWQ', 'customerID_0533-BNWKF', 'customerID_0533-UCAAU', 'customerID_0536-ACXIP', 'customerID_0536-BGFMZ', 'customerID_0536-ESJEP', 'customerID_0537-QYZZN', 'customerID_0541-FITGH', 'customerID_0547-HURJB', 'customerID_0549-CYCQN', 'customerID_0550-DCXLH', 'customerID_0556-FJEGU', 'customerID_0557-ASKVU', 'customerID_0559-CKHUS', 'customerID_0562-HKHML', 'customerID_0564-JJHGS', 'customerID_0564-MUUQK', 'customerID_0565-IYCGT', 'customerID_0565-JUPYD', 'customerID_0567-GGCAC', 'customerID_0568-ONFPC', 'customerID_0570-BFQHT', 'customerID_0572-ZJKLT', 'customerID_0575-CUQOV', 'customerID_0576-WNXXC', 'customerID_0577-WHMEV', 'customerID_0578-SKVMF', 'customerID_0580-PIQHM', 'customerID_0581-BXBUB', 'customerID_0582-AVCLN', 'customerID_0585-EGDDA', 'customerID_0587-DMGBH', 'customerID_0594-UFTUL', 'customerID_0595-ITUDF', 'customerID_0596-BQCEQ', 'customerID_0599-XNYDO', 'customerID_0603-OLQDC', 'customerID_0603-TPMIB', 'customerID_0604-THJFP', 'customerID_0607-DAAHE', 'customerID_0607-MVMGC', 'customerID_0608-JDVEC', 'customerID_0611-DFXKO', 'customerID_0612-RTZZA', 'customerID_0613-WUXUM', 'customerID_0616-ATFGB', 'customerID_0617-FHSGK', 'customerID_0618-XWMSS', 'customerID_0619-OLYUR', 'customerID_0620-DLSLK', 'customerID_0620-XEFWH', 'customerID_0621-CXBKL', 'customerID_0621-HJWXJ', 'customerID_0621-JFHOL', 'customerID_0621-TSSMU', 'customerID_0621-TWIEM', 'customerID_0623-GDISB', 'customerID_0623-IIHUG', 'customerID_0625-AFOHS', 'customerID_0626-QXNGV', 'customerID_0628-CNQRM', 'customerID_0634-SZPQA', 'customerID_0635-WKOLD', 'customerID_0637-UBJRP', 'customerID_0640-YJTPY', 'customerID_0641-EVBOJ', 'customerID_0644-OQMDK', 'customerID_0650-BWOZN', 'customerID_0654-PQKDW', 'customerID_0655-RBDUG', 'customerID_0655-YDGFJ', 'customerID_0657-DOGUM', 'customerID_0661-KQHNK', 'customerID_0661-XEYAN', 'customerID_0665-XHDJU', 'customerID_0666-UXTJO', 'customerID_0667-NSRGI', 'customerID_0670-KDOMA', 'customerID_0673-IGUQO', 'customerID_0674-DGMAQ', 'customerID_0674-EYYZV', 'customerID_0674-GCDXG', 'customerID_0675-NCDYU', 'customerID_0678-RLHVP', 'customerID_0679-IDSTG', 'customerID_0679-TDGAK', 'customerID_0682-USIXD', 'customerID_0684-AOSIH', 'customerID_0685-MLYYM', 'customerID_0687-ZVTHB', 'customerID_0690-SRQID', 'customerID_0691-IFBQW', 'customerID_0691-JVSYA', 'customerID_0691-NIKRI', 'customerID_0696-UKTOX', 'customerID_0697-ZMSWS', 'customerID_0699-NDKJM', 'customerID_0701-RFGFI', 'customerID_0704-VCUMB', 'customerID_0708-LGSMF', 'customerID_0708-SJDIS', 'customerID_0709-TVGUR', 'customerID_0716-BQNDX', 'customerID_0719-SYFRB', 'customerID_0722-SVSFK', 'customerID_0722-TROQR', 'customerID_0723-FDLAY', 'customerID_0723-VSOBE', 'customerID_0725-CXOTM', 'customerID_0727-BMPLR', 'customerID_0727-BNRLG', 'customerID_0727-IWKVK', 'customerID_0730-BGQGF', 'customerID_0730-KOAVE', 'customerID_0731-EBJQB', 'customerID_0733-VUNUW', 'customerID_0734-OXWBT', 'customerID_0739-UUAJR', 'customerID_0742-LAFQK', 'customerID_0742-MOABM', 'customerID_0743-HRVFF', 'customerID_0744-BIKKF', 'customerID_0744-GKNGE', 'customerID_0746-JTRFU', 'customerID_0748-RDGGM', 'customerID_0749-IRGQE', 'customerID_0750-EBAIU', 'customerID_0750-EKNGL', 'customerID_0754-EEBDC', 'customerID_0754-UKWQP', 'customerID_0756-MPZRL', 'customerID_0757-WCUUZ', 'customerID_0761-AETCS', 'customerID_0769-MURVM', 'customerID_0771-CHWSK', 'customerID_0771-WLCLA', 'customerID_0774-IFUVM', 'customerID_0774-RMNUW', 'customerID_0778-NELLA', 'customerID_0780-XNZFN', 'customerID_0781-LKXBR', 'customerID_0784-GTUUK', 'customerID_0784-ZQJZX', 'customerID_0786-VSSUD', 'customerID_0787-LHDYT', 'customerID_0788-DXBFY', 'customerID_0793-TWELN', 'customerID_0794-YVSGE', 'customerID_0795-GMVQO', 'customerID_0795-LAFGP', 'customerID_0795-XCCTE', 'customerID_0807-ZABDG', 'customerID_0810-BDHAW', 'customerID_0811-GSDTP', 'customerID_0812-WUPTB', 'customerID_0815-MFZGM', 'customerID_0816-TSPHQ', 'customerID_0817-HSUSE', 'customerID_0818-OCPZO', 'customerID_0820-FNRNX', 'customerID_0822-GAVAP', 'customerID_0822-QGCXA', 'customerID_0823-HSCDJ', 'customerID_0825-CPPQH', 'customerID_0827-ITJPH', 'customerID_0829-DDVLK', 'customerID_0831-JNISG', 'customerID_0835-JKADZ', 'customerID_0836-SEYLU', 'customerID_0839-JTCUD', 'customerID_0839-QNXME', 'customerID_0840-DCNZE', 'customerID_0840-DFEZH', 'customerID_0842-IWYCP', 'customerID_0843-WTBXE', 'customerID_0847-HGRML', 'customerID_0848-ZGQIJ', 'customerID_0851-DFJKB', 'customerID_0853-TWRVK', 'customerID_0854-UYHZD', 'customerID_0859-YGKFW', 'customerID_0862-PRCBS', 'customerID_0866-QLSIR', 'customerID_0867-LDTTC', 'customerID_0867-MKZVY', 'customerID_0868-VJRDR', 'customerID_0869-PAPRP', 'customerID_0871-OPBXW', 'customerID_0871-URUWO', 'customerID_0872-CASZJ', 'customerID_0872-JCPIB', 'customerID_0872-NXJYS', 'customerID_0875-CABNR', 'customerID_0877-SDMBN', 'customerID_0880-FVFWF', 'customerID_0880-TKATG', 'customerID_0885-HMGPY', 'customerID_0886-QGENL', 'customerID_0887-HJGAR', 'customerID_0895-DQHEW', 'customerID_0895-LMRSF', 'customerID_0895-LNKRC', 'customerID_0897-FEGMU', 'customerID_0898-XCGTF', 'customerID_0899-LIIBW', 'customerID_0899-WZRSD', 'customerID_0902-RFHOF', 'customerID_0902-XKXPN', 'customerID_0906-QVPMS', 'customerID_0907-HQNTS', 'customerID_0909-SDHNU', 'customerID_0909-SELIE', 'customerID_0913-XWSCN', 'customerID_0916-KNFAJ', 'customerID_0916-QOFDP', 'customerID_0921-OHLVP', 'customerID_0924-BJCRC', 'customerID_0925-VYDLG', 'customerID_0927-CNGRH', 'customerID_0927-LCSMG', 'customerID_0928-JMXNP', 'customerID_0928-XUTSN', 'customerID_0929-HYQEW', 'customerID_0930-EHUZA', 'customerID_0931-MHTEM', 'customerID_0932-YIXYU', 'customerID_0936-NQLJU', 'customerID_0939-EREMR', 'customerID_0939-YAPAF', 'customerID_0940-OUQEC', 'customerID_0943-ZQPXH', 'customerID_0945-TSONX', 'customerID_0946-FKYTX', 'customerID_0947-IDHRQ', 'customerID_0947-MUGVO', 'customerID_0952-KMEEH', 'customerID_0956-ACVZC', 'customerID_0958-YHXGP', 'customerID_0959-WHOKV', 'customerID_0960-HUWBM', 'customerID_0961-ZWLVI', 'customerID_0962-CQPWQ', 'customerID_0968-GSIKN', 'customerID_0969-RGKCU', 'customerID_0970-QXPXW', 'customerID_0971-QIFJK', 'customerID_0973-KYVNF', 'customerID_0975-UYDTX', 'customerID_0975-VOOVL', 'customerID_0979-MOZQI', 'customerID_0979-PHULV', 'customerID_0980-FEXWF', 'customerID_0980-PVMRC', 'customerID_0983-TATYJ', 'customerID_0988-JRWWP', 'customerID_0991-BRRFB', 'customerID_0993-OSGPT', 'customerID_0999-QXNSA', 'customerID_1004-NOZNR', 'customerID_1009-IRMNA', 'customerID_1010-DIAUQ', 'customerID_1013-QCWAM', 'customerID_1015-JPFYW', 'customerID_1015-OWJKI', 'customerID_1016-DJTSV', 'customerID_1017-FBQMM', 'customerID_1020-JPQOW', 'customerID_1022-RKXDR', 'customerID_1023-BQXZE', 'customerID_1024-KPRBB', 'customerID_1024-VRZHF', 'customerID_1025-FALIX', 'customerID_1027-LKKQQ', 'customerID_1028-FFNJK', 'customerID_1031-IIDEO', 'customerID_1032-MAELW', 'customerID_1036-GUDCL', 'customerID_1038-RQOST', 'customerID_1041-RXHRA', 'customerID_1042-HFUCW', 'customerID_1043-UXOVO', 'customerID_1043-YCUTE', 'customerID_1045-LTCYT', 'customerID_1047-NNCBF', 'customerID_1047-RNXZV', 'customerID_1049-FYSYG', 'customerID_1051-EQPZR', 'customerID_1051-GEJLJ', 'customerID_1052-QJIBV', 'customerID_1057-FOGLZ', 'customerID_1060-ENTOF', 'customerID_1061-PNTHC', 'customerID_1062-LHZOD', 'customerID_1063-DHQJF', 'customerID_1064-FBXNK', 'customerID_1066-JKSGK', 'customerID_1069-QJOEE', 'customerID_1069-XAIEM', 'customerID_1073-XXCZD', 'customerID_1074-WVEVG', 'customerID_1075-BGWOH', 'customerID_1077-HUUJM', 'customerID_1078-TDCRN', 'customerID_1080-BWSYE', 'customerID_1084-MNSMJ', 'customerID_1084-UQCHV', 'customerID_1085-LDWAM', 'customerID_1086-LXKFY', 'customerID_1087-GRUYI', 'customerID_1087-UDSIH', 'customerID_1088-AUUZZ', 'customerID_1088-CNNKB', 'customerID_1089-HDMKP', 'customerID_1089-XZWHH', 'customerID_1090-ESELR', 'customerID_1090-PYKCI', 'customerID_1091-SOZGA', 'customerID_1092-WPIVQ', 'customerID_1093-YSWCA', 'customerID_1094-BKOSX', 'customerID_1095-WGNGG', 'customerID_1096-ADRUX', 'customerID_1097-FSPVW', 'customerID_1098-KFQEC', 'customerID_1098-TDVUQ', 'customerID_1101-SSWAG', 'customerID_1104-FEJAM', 'customerID_1104-TNLZA', 'customerID_1106-HRLKZ', 'customerID_1110-KYLGQ', 'customerID_1113-IUJYX', 'customerID_1114-CENIM', 'customerID_1116-DXXDF', 'customerID_1116-FRYVH', 'customerID_1120-BMWUB', 'customerID_1121-QSIVB', 'customerID_1122-JWTJW', 'customerID_1122-YJBCS', 'customerID_1125-SNVCK', 'customerID_1131-ALZWV', 'customerID_1131-QQZEB', 'customerID_1131-SUEKT', 'customerID_1133-KXCGE', 'customerID_1134-YWTYF', 'customerID_1135-HIORI', 'customerID_1135-LMECX', 'customerID_1136-XGEQU', 'customerID_1137-DGOWI', 'customerID_1139-WUOAH', 'customerID_1140-UKVZG', 'customerID_1142-IHLOO', 'customerID_1142-WACZW', 'customerID_1143-NMNQJ', 'customerID_1150-FTQGN', 'customerID_1150-WFARN', 'customerID_1153-GNOLC', 'customerID_1154-HYWWO', 'customerID_1156-ZFYDO', 'customerID_1157-BQCUW', 'customerID_1162-ECVII', 'customerID_1163-ONYEY', 'customerID_1163-VIPRI', 'customerID_1169-SAOCL', 'customerID_1169-WCVAK', 'customerID_1170-SASML', 'customerID_1171-TYKUR', 'customerID_1172-VIYBP', 'customerID_1173-XZPYF', 'customerID_1177-XZBJL', 'customerID_1178-PZGAB', 'customerID_1179-INLAT', 'customerID_1183-CANVH', 'customerID_1184-PJVDB', 'customerID_1187-WILMM', 'customerID_1193-RTSLK', 'customerID_1194-BHJYC', 'customerID_1194-HVAIF', 'customerID_1195-OIYEJ', 'customerID_1196-AMORA', 'customerID_1200-TUZHR', 'customerID_1206-EHBDD', 'customerID_1208-DNHLN', 'customerID_1209-VFFOC', 'customerID_1213-NGCUN', 'customerID_1215-EXRMO', 'customerID_1215-VFYVK', 'customerID_1216-BGTSP', 'customerID_1216-JWVUX', 'customerID_1217-VASWC', 'customerID_1218-VKFPE', 'customerID_1221-GHZEP', 'customerID_1222-LRYKO', 'customerID_1223-UNPKS', 'customerID_1226-JZNKR', 'customerID_1226-UDFZR', 'customerID_1227-UDMZR', 'customerID_1228-FZFRV', 'customerID_1228-ZLNBX', 'customerID_1229-RCALF', 'customerID_1230-QAJDW', 'customerID_1231-YNDEK', 'customerID_1236-WFCDV', 'customerID_1237-WIYYZ', 'customerID_1240-HCBOH', 'customerID_1240-KNSEZ', 'customerID_1241-EZFMJ', 'customerID_1241-FPMOF', 'customerID_1245-HARPS', 'customerID_1247-QBVSH', 'customerID_1248-DYXUB', 'customerID_1251-KRREG', 'customerID_1251-STYSZ', 'customerID_1254-IZEYF', 'customerID_1257-SXUXQ', 'customerID_1258-YMZNM', 'customerID_1261-FWTTE', 'customerID_1262-OPMFY', 'customerID_1264-BYWMS', 'customerID_1265-BCFEO', 'customerID_1265-XTECC', 'customerID_1268-ASBGA', 'customerID_1269-FOYWN', 'customerID_1271-SJBGZ', 'customerID_1272-ILHFG', 'customerID_1273-MTETI', 'customerID_1282-IHQAC', 'customerID_1285-OKIPP', 'customerID_1291-CUOCY', 'customerID_1293-BSEUN', 'customerID_1293-HHSHJ', 'customerID_1297-VQDRP', 'customerID_1298-PHBTI', 'customerID_1299-AURJA', 'customerID_1301-LOPVR', 'customerID_1302-UHBDD', 'customerID_1303-SRDOK', 'customerID_1304-SEGFY', 'customerID_1306-RPWXZ', 'customerID_1307-ATKGB', 'customerID_1307-TVUFB', 'customerID_1309-BXVOQ', 'customerID_1309-XGFSN', 'customerID_1310-QRITU', 'customerID_1319-YLZJG', 'customerID_1320-GVNHT', 'customerID_1320-HTRDR', 'customerID_1320-REHCS', 'customerID_1322-AGOQM', 'customerID_1323-OOEPC', 'customerID_1325-USMEC', 'customerID_1328-EUZHC', 'customerID_1329-VHWNP', 'customerID_1334-FJSVR', 'customerID_1334-PDUKM', 'customerID_1335-HQMKX', 'customerID_1335-MXCSE', 'customerID_1336-EZFZY', 'customerID_1337-BOZWO', 'customerID_1338-CECEE', 'customerID_1345-GKDZZ', 'customerID_1345-ZUKID', 'customerID_1346-PJWTK', 'customerID_1347-KTTTA', 'customerID_1349-WXNGG', 'customerID_1352-HNSAW', 'customerID_1352-VHKAJ', 'customerID_1354-YZFNB', 'customerID_1357-BIJKI', 'customerID_1357-MVDOZ', 'customerID_1360-XFJMR', 'customerID_1363-TXLSL', 'customerID_1370-GGAWX', 'customerID_1371-DWPAZ', 'customerID_1371-OJCEK', 'customerID_1371-WEPDS', 'customerID_1373-ORVIZ', 'customerID_1374-DMZUI', 'customerID_1376-HHBDV', 'customerID_1379-FRVEB', 'customerID_1384-RCUXW', 'customerID_1385-TQOZW', 'customerID_1386-ZIKUV', 'customerID_1389-CXMLU', 'customerID_1389-WNUIB', 'customerID_1391-UBDAR', 'customerID_1393-IMKZG', 'customerID_1394-SUIUH', 'customerID_1395-OFUWC', 'customerID_1396-QWFBJ', 'customerID_1397-XKKWR', 'customerID_1399-OUPJN', 'customerID_1399-UBQIU', 'customerID_1400-MMYXY', 'customerID_1400-WIVLL', 'customerID_1402-PTHGN', 'customerID_1403-GYAFU', 'customerID_1403-LKLIK', 'customerID_1406-PUQVY', 'customerID_1407-DIGZV', 'customerID_1415-YFWLT', 'customerID_1421-HCERK', 'customerID_1422-DGUBX', 'customerID_1423-BMPBQ', 'customerID_1427-VERSM', 'customerID_1428-GTBJJ', 'customerID_1429-UYJSV', 'customerID_1430-SFQSA', 'customerID_1431-AID

In [96]:
Y_train

2142     No
1623     No
6074    Yes
1362    Yes
6754     No
       ...
3772    Yes
5191     No
5226     No
5390    Yes
860      No
Name: Churn, Length: 5634, dtype: object

In [97]:
Y_test

185     Yes
2715     No
3825     No
1807    Yes
132      No
       ...
6366     No
315      No
2439     No
5002     No
1161    Yes
Name: Churn, Length: 1409, dtype: object

In [98]:
X_train_Combined

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,TotalCharges,customerID_0002-ORFBO,customerID_0003-MKNFE,customerID_0004-TLHLJ,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
2142,0,0,1,21,1,0,1336.80,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1623,0,0,0,54,1,1,5129.45,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
6074,0,1,0,1,0,1,23.45,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1362,0,0,0,4,1,1,237.95,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6754,0,0,1,0,1,1,0.00,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,0,1,0,1,1,1,95.00,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
5191,0,1,1,23,1,1,2198.30,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
5226,0,1,1,12,1,1,306.05,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
5390,1,0,0,12,1,1,1200.15,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
860,0,0,0,26,1,0,457.30,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [99]:
X_test_Combined

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,TotalCharges,customerID_0002-ORFBO,customerID_0003-MKNFE,customerID_0004-TLHLJ,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
185,0,1,0,1,0,1,24.80,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2715,0,0,0,41,1,1,996.45,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3825,0,1,1,52,1,0,1031.70,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1807,0,0,0,1,1,0,76.35,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
132,0,0,0,67,1,0,3260.10,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,0,1,0,64,1,1,4378.80,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
315,0,1,1,51,1,0,5686.40,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2439,0,1,1,17,1,0,329.75,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
5002,0,1,1,69,0,1,2960.10,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1161,0,0,1,1,0,1,31.35,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

##### Choice Of Model To Predict Customer Churn And Know Ahead Of Time Which Telco Customers Are Likely To cancel Their Service 
##### As Requested By The Retention Team For Their Report - 
##### RANDOM FOREST CLASSIFIER ALGORITHM MODEL

##### Reasoning And Decision For The Choice Of Random Forest Classifier Algorithm

In [100]:
#    THE DATASET

# 1. The Telco Customer Churn Dataset is a combination of different categories of features (X) data values with 21 columns, 
#....and a target column (Y).

# 2. The break-down of the different categories of the data values and their data types shows some of the feature columns 
#....with continuous numerical values, combined with other categorical columns with simple binary values and multiple
#....categories of texts, as well as simple and more complex binary values. 

# 3  The dataset are also labelled with inputs resulting in known outputs, as the predictor columns for a supervised classification
#... learning.

# 4  The labelled datasets show the relationship between inputs and outputs (independent i.e. features (X) and dependent i.e.
#....target (Y) values, for predicting a categorical values of target (Y) and labels of unseen and new data, with the Decision
#.... Tree Classifier machine learning algorithm, wherein inputs result in known outputs when a machine model learns and trains
#....the datasets with the predictor values, using the model, considered appropriate for customers decision to cancel or retain
#....services.

#    THE DECISION FOR THE RANDOM FOREST CLASSIFIER MODEL AS THE APPROPRIATE ALGORITHM FOR BUILDING A PREDICTIVE MODEL

# 1. The categorical numerical 'churn' column values cleary and definitely support the use of a classification model, and 
#....specifically the Random Forest Algorithm model to determine a course action, for multiple decision occurrences like 
#....like voting to establish the most or majority decision.

# 2. The multiple split decision nodes of Random Forest Classifier model on the 'churn' question, to cancel services (YES)
#....or not to cancel (NO) by Telco customers, with a more reliable prediction of the outcome ahead of time, is important 
#....for the Retention Team to proactively contact the predicted customers and avoid a negative impact on the business with
#....a huge customer turnover and the revenue generation capacity of Telco business.

#....The Random Forest Classifier Algorithm is considered a better trade-off with Decision Tree Classifier Algorithm because 
#....it is an ensembling learning algorithm that builds on a collection of multiple decision trees with decision nodes, and 
#....combines the output to establish majority for the course of action. It is therefore a more robust and reliable algorithm,
#....and has a higher level of accuracy, unlike the Decision tree classifier algorithm that builds with a single decision tree. 

#....The multiple decision nodes give an edge with several decision trees voting and filtering instead of just a single decision,
#....based on the number of estimators.


# 3. The Retention Team's request to know which customers are likely to churn and cancel their subscriptions,in order to find a way 
#....to flag such customers, so they can be contacted proactively, can therefore be addressed, using the predicted outcome from the 
#....Random Forest Classifier model.

##### Importing The Machine Learning Random Forest Classifier Algorithm To Use For The Model

In [144]:
from sklearn.ensemble import RandomForestClassifier

##### Creating An Instance Of The Model

In [147]:
RandomForestClassifier()

RTModel = RandomForestClassifier(n_jobs = -1, n_estimators = 200, max_depth = None, random_state = 42)

##### Fitting The Training Set On The Model

In [148]:
RTModel.fit(X_train_Combined, Y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [149]:
y_predictions = RTModel.predict(X_test_Combined)

In [150]:
print(type(y_predictions))
print(y_predictions.shape)
print(y_predictions[:5])

<class 'numpy.ndarray'>
(1409,)
['Yes' 'No' 'No' 'Yes' 'No']

##### Observation Of The Prediction Results Or Outcomes About Knowing Telco Customers That Are Likely To Cancel Their Subscribed 
##### Services For The Request Of The Retention Team Of FreshWave Telecom To Contact Them Proactively.

In [151]:
# 1. The Retention Team Model (RTModel) predicted how to know Telco customers that are likely to cancel their subscriptions 
#....on categorical values of YES and NO.

# 2. The predicted outcome justifies the trade-off and the decision for the use RandomForestClassifier algorithm to build the model
#....for presentation to the Retention Team.

##### Checking To Confirm The Values Of The Variables Trained, Fitted, Predicted And Tested

In [152]:
X_train_Combined.shape

(5634, 5672)

In [153]:
X_test_Combined.shape

(1409, 5672)

In [154]:
Y_train.shape

(5634,)

In [155]:
Y_test.shape

(1409,)

In [156]:
print('X_test_Combined:', X_test_Combined.shape)
print('Y_test:', Y_test.shape)
print('y_predictions:', y_predictions.shape)

X_test_Combined: (1409, 5672)
Y_test: (1409,)
y_predictions: (1409,)

In [157]:
print(type(y_predictions))
print(y_predictions)

<class 'numpy.ndarray'>
['Yes' 'No' 'No' ... 'No' 'No' 'No']

##### Baseline Evaluation - The Retention Team RandomForestClassifier Model With Relevant And Appropriate Metrics - Accuracy Score, 
##### Precision Score, Recall Score, F1-Score, and Confusion Matrix

In [158]:
from sklearn.metrics import (accuracy_score, recall_score, f1_score, confusion_matrix)

In [159]:
from sklearn.metrics import precision_score

In [160]:
print('Accuracy:', accuracy_score(Y_test, y_predictions))
print('Precision:', precision_score(Y_test, y_predictions, pos_label='Yes'))
print('Recall:', recall_score(Y_test, y_predictions, pos_label='Yes'))
print('F1 Score:', f1_score(Y_test, y_predictions, pos_label='Yes'))

print(confusion_matrix(Y_test, y_predictions, labels =['No', 'Yes']))

Accuracy: 0.7991483321504613
Precision: 0.6717557251908397
Recall: 0.4718498659517426
F1 Score: 0.5543307086614173
[[950  86]
 [197 176]]

##### Interpretation Of RTModel Evaluation

In [195]:
# 1. Accuracy Score: 0.7991483321504613 - Approximately 79.91%

#....79.91% of the customers were correctly classified as likely to cancel their subscription or not cancel
#... This means the model correctly identified customers likely to churn or not. However, the request from the Retention Team 
#....is to specifically find a way to know and identufy customers that will likely ans almost certainly cancel subscription/churn. 
#.... Since this is not clearly and reliably shown, other metrics below are required to confirm the predictions as required. 

# 2. Precision Score: 0.6717557251908397 - Approximately 67.17%

#....67.18% indicates a fairly high performance of the model to correctly predict the number of Telco customers that will actually
#....cancel their subscription. The correctness of its predictionn however does not identify the customers as required. it means
#....other metrics are required specifically for the requst, even thouhg the pecision score is also useful to confirm reliability
#....on the correctness of the predictions of the model.

# 3.  Recall Score: 0.4718498659517426 - Approximately 47.18%

#....The recall score of 47.18% shows the model correctly identified only of customers who actually canselled their subscriptions
#....and missed 52.82% of the number that actuall cancelled. This score is therefore too low for the Retention team to proactively
#....make contacts with all those likely to cancel for effective remedial actions to the remaining 52.82%. 

# 4. F1 score: 0.5543307086614173 - Approximately 55.43%

#....The  very low recall score F1 score combines both precision and recall scores to compensate and balance out the predictions. 
#....The score is quite low given the very low recall score that brought down the precision score. It ultimately indicates a 
#.... with regards to moderately or fairly identifying customers that actually cancelled subscriptions and avoiding wrongly
#....identifying customers and creating false alarm.

# 5.  Confusion Matrix: 
#      [[950  86]
#       [197 176]] 
#..... 197 customers were missed but actually cancelled. 
# .... 176 were correctly identified to cancel and they did.
#..... 950 correctly identified not to cancel
# ....  86 were wrongly identified to cancel


#     Summary Of The Interpretation

# 5. The Retention Team Model (RTModel)  is to an extent a reasonably accurate model that is able to correctly predict and identify
#....customers that are likely to churn, and cancel their subscriptions. The margin of missed customers from the actual total is 
#....large and significant. The errors require further tuning of the model with varied parameters as shown below, with as many trials
#.... as possible to get a perfect fit of the model with a better, reliable and more accurate predictions.
#....That is the way to fully address the concerns of the Retention Team and assist to build a model with better level of performance
#.... with more accurate predictions. The combined metrics show that reliance cannot be placed on only the high accuracy score of 79.91%
#.... The encouraging thing about the model is the 67.18% precision of identifying customers that are likely to cancel their services.

# 6.  Analysing Test Results Of The Model

#.... 1409 customers were tested with the results results as follows:
#.... Out of which 1,036 did not cancel their sevices
#.... 373 actually cancelled
#.... 176 custmers that actually cancelled were correctly identified by the model
#.... 197 customers that actually also cancelled were missed by the model
#..... 86 customers were wrongly identified and flagged to likely cancel, but did not.

#     Recommendation

#     It is important to continue tuning the model with different parameters to a achieve a higher better and improved performance level

#... It is also necessary to consider other ways to further support the above metrics like probability count below to meet the requirements 
#....of the Retention Team

##### Probability Approach With The RTModel To Identify Customers Likely To Cancel Subscriptions For The Retention Team

In [ ]:
y_predictions = RTModel.predict(X_test)
churn_probability = model.predict_proba(X_test)[:, 1]
print(churn_probability[:10])

In [ ]:
High_risk_customers = churn_results[churn_results['churn_Probability'] >= 0.70]

In [ ]:
print(High_risk_customers)

In [128]:
#  RTModel - Random Forest Clssifier Algorithm Model 

#  Baseline Churn Model Parameters
#  n_estimators = 200
#  max_depth = None
#  random_state = 42

In [ ]:
#    Baseline Random Forest Evaluation Metrics

#    Accuracy: 0.7991483321504613 - (79.91%0
#    Precision: 0.6717557251908397 - (67.18%)
#    Recall: 0.4718498659517426 - (47.18%)
#    F1 Score: 0.5543307086614173 - (55.43%)

#    Confusion Matrix:
#    [[950  86]
#    [197 176]]

In [120]:
print('Accuracy:', accuracy_score(Y_test, y_predictions))

Accuracy: 0.7991483321504613

In [121]:
print('Recall:', recall_score(Y_test, y_predictions, pos_label='Yes'))

Recall: 0.4718498659517426

In [122]:
print('F1 Score:', f1_score(Y_test, y_predictions, pos_label='Yes'))

F1 Score: 0.5543307086614173

In [123]:
CMatrix = confusion_matrix(Y_test, y_predictions, labels = ['No', 'Yes'])

print('Confusion matrix:')
print(CMatrix)

Confusion matrix:
[[950  86]
 [197 176]]

#####  Building  And Tuning RTModel2 RandomForestClassifier With A Different Number Of Estimators and  Max-Depth Value To See The 
#####  Difference In Predictions For Comparison -  For 2nd Trial Experiment And Possibly More, To Have The Desired Improvement For
#####  A Final Model

In [133]:
print('Accuracy:', accuracy_score(Y_test, y_pred))
print('Precision:', precision_score(Y_test, y_pred, pos_label='Yes'))
print('Recall:', recall_score(Y_test, y_pred, pos_label='Yes'))
print('F1 Score:', f1_score(Y_test, y_pred, pos_label='Yes'))

print(confusion_matrix(Y_test, y_pred, labels =['No', 'Yes']))

Accuracy: 0.7374024130589071
Precision: 1.0
Recall: 0.00804289544235925
F1 Score: 0.015957446808510637
[[1036    0]
 [ 370    3]]

In [ ]:
#  RTModel2 - Random Forest Clssifier Algorithm Model 

#  Baseline Churn Model Parameters
#  n_estimators = 300
#  max_depth = 10
#  random_state = 42

In [ ]:
#  RTModel2 - Evaluation Metrics Evaluation

#  Accuracy: 0.7374024130589071
#  Precision: 1.0
#  Recall: 0.00804289544235925
#  F1 Score: 0.015957446808510637
#  [[1036    0]
#  [ 370    3]]

#####  Building  And Tuning RTModel3 RandomForestClassifier With A Different Number Of Estimators and  Max-Depth Value To See The 
#####  Difference In Predictions For Comparison -  For 3rd Trial Experiment And Possibly More, To Have The Desired Improvement For
#####  A Final Model

In [139]:
print('Accuracy:', accuracy_score(Y_test, y_predictn))
print('Precision:', precision_score(Y_test, y_predictn, pos_label='Yes'))
print('Recall:', recall_score(Y_test, y_predictn, pos_label='Yes'))
print('F1 Score:', f1_score(Y_test, y_predictn, pos_label='Yes'))

print(confusion_matrix(Y_test, y_predictn, labels =['No', 'Yes']))

Accuracy: 0.7629524485450674
Precision: 0.8679245283018868
Recall: 0.12332439678284182
F1 Score: 0.215962441314554
[[1029    7]
 [ 327   46]]

In [ ]:
#  RTModel3 - Random Forest Clssifier Algorithm Model 

#  Baseline Churn Model Parameters
#  n_estimators = 400
#  max_depth = 12
#  random_state = 42

In [140]:
#  RTModel3 - Evaluation Metrics  

#   Accuracy: 0.7629524485450674
#   Precision: 0.8679245283018868
#   Recall: 0.12332439678284182
#   F1 Score: 0.215962441314554
#   [[1029    7]
#   [ 327   46]]